import {chromium,expect} from '@playwright/test';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import {readFile,writeFile} from 'node:fs/promises';
import {PosEngine} from '../../src/pos/engine.ts';

async function createLegacyCaja(password:string){
 const runtime=JSON.parse(await readFile('.local/e2e-runtime.json','utf8')) as {directory:string};
 const legacy=await PosEngine.open(resolve(runtime.directory,'pos'),'http://127.0.0.1:4320');
 try{
  const login=await legacy.login('e2e-owner',password);
  if(!login.needsEnrollment)throw new Error('La caja sintética ya estaba vinculada.');
  const device=login.devices?.find(d=>d.branchName==='Milán');
  if(!device)throw new Error('No se encontró la caja sintética de Milán.');
  await legacy.enroll(device.id,'e2e-owner');
  await legacy.execute('e2e-owner','shift.open',{operationId:randomUUID(),openingCash:'25000'});
 }finally{legacy.close();}
}
export async function exerciseBrowser(password:string){
 await createLegacyCaja(password);
 const directory=resolve('.local/browser-e2e-'+randomUUID());
 let context=await chromium.launchPersistentContext(directory,{channel:'msedge',headless:true,viewport:{width:1440,height:1000}});
 try{
  let page=context.pages()[0]!;await page.goto('http://127.0.0.1:4320/');await page.getByLabel('Usuario',{exact:true}).fill('e2e-owner');await page.getByLabel('Contraseña',{exact:true}).fill(password);await page.getByRole('button',{name:'Entrar a Nativos'}).click();await expect(page.getByRole('heading',{name:'Hola, Equipo'})).toBeVisible();await page.getByRole('link',{name:'Caja y ventas'}).click();await expect(page.getByRole('heading',{name:'Activa esta caja'})).toBeVisible();const offlinePassword=page.getByLabel('Contraseña para habilitar Caja sin conexión');if(await offlinePassword.isVisible())await offlinePassword.fill(password);
  // The response is lost after the server commits. Retrying must use the same browser target and preserve the old writer.
  let interrupted=false;await page.route('**/api/local-transition',async route=>{await route.fetch();interrupted=true;await route.abort();});await page.getByRole('button',{name:'Trasladar caja anterior'}).click();await expect(page.getByRole('alert')).toBeVisible();expect(interrupted).toBeTruthy();await page.unrouteAll();await page.getByRole('button',{name:'Trasladar caja anterior'}).click();await expect(page.getByRole('heading',{name:'Nueva venta'})).toBeVisible();await page.getByRole('navigation').getByRole('button',{name:'Turno',exact:true}).click();await expect(page.locator('.pos-shift')).toContainText('25.000');await page.getByRole('navigation').getByRole('button',{name:'Venta',exact:true}).click();
  await page.getByRole('button',{name:'Salir',exact:true}).click();await context.setOffline(true);await page.reload();await page.getByLabel('Usuario',{exact:true}).fill('e2e-owner');await page.getByLabel('Contraseña',{exact:true}).fill(password);await page.getByRole('button',{name:'Entrar a caja'}).click();await expect(page.getByRole('heading',{name:'Nueva venta'})).toBeVisible();await page.getByRole('navigation').getByRole('button',{name:'Turno',exact:true}).click();await expect(page.locator('.pos-shift')).toContainText('25.000');await context.setOffline(false);await page.getByRole('navigation').getByRole('button',{name:'Venta',exact:true}).click();
  let dialog=page.getByRole('dialog');
  await page.getByRole('button').filter({hasText:'Batido de prueba'}).click();await dialog.getByLabel('Cantidad',{exact:true}).fill('2');await dialog.getByRole('button',{name:'Guardar en pedido'}).click();await expect(dialog).not.toBeVisible();await page.getByRole('button',{name:'Datos del pedido'}).click();const customer=await dialog.getByLabel('Cliente',{exact:true}).locator('option').evaluateAll(o=>o.find(x=>x.textContent?.startsWith('Cliente E2E'))!.getAttribute('value')!);await dialog.getByLabel('Cliente',{exact:true}).selectOption(customer);await dialog.getByRole('button',{name:'Guardar pedido',exact:true}).click();await expect(dialog).not.toBeVisible();await page.getByRole('button',{name:'Sincronizar',exact:true}).click();await expect(page.locator('.pos-sync')).toContainText('0 pendientes');await page.evaluate(()=>navigator.serviceWorker.ready.then(()=>true));
  await context.setOffline(true);await page.reload();await expect(page.getByRole('region',{name:'Pedido'})).toContainText('2 × Batido');await expect(page.getByRole('button',{name:'+ Nuevo producto'})).toBeDisabled();
  // Force IndexedDB abort before commit: no receipt or partial sale may survive.
  await page.evaluate(()=>{const original=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(...args:Parameters<IDBDatabase['transaction']>){const t=original.apply(this,args);if(args[1]==='readwrite')queueMicrotask(()=>t.abort());return t;};});
  await page.getByRole('button',{name:'Cobrar pedido',exact:true}).click();await page.getByLabel('Importe 1 (COP)').fill('100000');await page.getByRole('button',{name:'Confirmar cobro'}).click();await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible();await page.reload();await expect(page.getByRole('region',{name:'Pedido'})).toContainText('2 × Batido');
  const second=await context.newPage();await second.goto('http://127.0.0.1:4320/caja');
  for(const p of [page,second]){await p.getByRole('button',{name:'Cobrar pedido',exact:true}).click();await expect(p.getByLabel('Puntos a canjear')).toBeDisabled();await p.getByLabel('Importe 1 (COP)').fill('100000');}
  await Promise.all([page.getByRole('button',{name:'Confirmar cobro'}).click(),second.getByRole('button',{name:'Confirmar cobro'}).click()]);
  await expect.poll(async()=>Number(await page.getByRole('heading',{name:'Comprobante interno'}).isVisible())+Number(await second.getByRole('heading',{name:'Comprobante interno'}).isVisible())).toBe(1);
  // A newly installed worker waits while this client has an unsynchronized sale; it never deletes IndexedDB.
  const workerPath=resolve('dist/sw.js'),workerSource=await readFile(workerPath,'utf8');
  // La venta sigue pendiente y el comprobante abierto pausa el sincronizador. Se
  // habilita red sólo para que el navegador pueda descargar el nuevo worker.
  await context.setOffline(false);
  try{await writeFile(workerPath,workerSource+`\n// E2E pending-update ${randomUUID()}\n`);const waiting=await page.evaluate(async()=>{const registration=await navigator.serviceWorker.getRegistration('/');if(!registration)throw new Error('No hay service worker registrado.');await registration.update();await new Promise<void>((resolve,reject)=>{const done=()=>resolve();if(registration.waiting)return done();const installing=registration.installing;if(installing)installing.addEventListener('statechange',()=>installing.state==='installed'?done():undefined,{once:true});else registration.addEventListener('updatefound',()=>registration.installing?.addEventListener('statechange',()=>registration.installing?.state==='installed'?done():undefined,{once:true}),{once:true});setTimeout(()=>reject(new Error('La actualización del service worker no terminó.')),20000);});return Boolean(registration.waiting)&&navigator.serviceWorker.controller?.scriptURL.endsWith('/sw.js');});expect(waiting).toBeTruthy();}finally{await writeFile(workerPath,workerSource);}
  await context.close();context=await chromium.launchPersistentContext(directory,{channel:'msedge',headless:true,offline:true,viewport:{width:1440,height:1000}});page=context.pages()[0]!;await page.goto('http://127.0.0.1:4320/caja');await expect(page.getByRole('heading',{name:'Nueva venta'})).toBeVisible();await page.getByRole('navigation').getByRole('button',{name:'Comprobantes',exact:true}).click();await expect(page.getByRole('button',{name:'Ver copia'})).toHaveCount(1);await page.getByRole('button',{name:'Ver copia'}).click();await expect(page.getByRole('dialog')).toContainText('Pendientes de sincronización');await page.screenshot({path:'docs/evidence/unified-web/offline-restart-receipt.png',fullPage:true});await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Salir',exact:true}).click();await page.getByLabel('Usuario',{exact:true}).fill('e2e-owner');await page.getByLabel('Contraseña',{exact:true}).fill('incorrecta');await page.getByRole('button',{name:'Entrar a caja'}).click();await expect(page.getByRole('alert')).toContainText('Credenciales offline incorrectas');await page.getByLabel('Contraseña',{exact:true}).fill(password);await page.getByRole('button',{name:'Entrar a caja'}).click();await expect(page.getByRole('heading',{name:'Comprobantes',exact:true})).toBeVisible();await page.getByRole('navigation').getByRole('button',{name:'Comprobantes',exact:true}).click();
  await context.setOffline(false);await page.getByRole('button',{name:'Sincronizar',exact:true}).click();await expect(page.locator('.pos-sync')).toContainText('0 pendientes');await page.getByRole('button',{name:'Sincronizar',exact:true}).click();await expect(page.getByRole('button',{name:'Ver copia'})).toHaveCount(1);
  await page.getByRole('navigation').getByRole('button',{name:'Venta',exact:true}).click();await page.getByRole('button').filter({hasText:'Batido de prueba'}).click();dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Guardar en pedido'}).click();await expect(dialog).not.toBeVisible();await page.getByRole('button',{name:'Datos del pedido'}).click();await dialog.getByLabel('Cliente',{exact:true}).selectOption(customer);await dialog.getByRole('button',{name:'Guardar pedido',exact:true}).click();await expect(dialog).not.toBeVisible();await page.getByRole('button',{name:'Sincronizar',exact:true}).click();await expect(page.locator('.pos-sync')).toContainText('0 pendientes');
  let lost=false;await page.route('**/api/pos/sync',async route=>{const b=route.request().postDataJSON();if(!lost&&JSON.parse(b.payload).loyalty?.redeemedPoints==='1'){const response=await route.fetch();expect(response.status()).toBe(200);lost=true;await route.abort();}else await route.continue();});
  await page.getByRole('button',{name:'Cobrar pedido',exact:true}).click();await dialog.getByLabel('Puntos a canjear').fill('1');await dialog.getByLabel('Importe 1 (COP)').fill('100000');await dialog.getByRole('button',{name:'Confirmar cobro'}).click();await expect(page.getByRole('button',{name:'Recuperar cobro'})).toBeVisible();expect(lost).toBeTruthy();await context.setOffline(true);await page.reload();await expect(page.getByRole('button',{name:'Recuperar cobro'})).toBeVisible();await page.screenshot({path:'docs/evidence/unified-web/pending-redemption.png',fullPage:true});await context.setOffline(false);await page.unrouteAll();await page.getByRole('button',{name:'Recuperar cobro'}).click();await expect(page.getByRole('heading',{name:'Comprobante interno'})).toBeVisible();await page.keyboard.press('Escape');await page.getByRole('navigation').getByRole('button',{name:'Comprobantes',exact:true}).click();await expect(page.getByRole('button',{name:'Ver copia'})).toHaveCount(2);
  await context.setOffline(true);const expired=await context.newPage();await expired.addInitScript(()=>{const now=Date.now.bind(Date);Date.now=()=>now()+8*24*3600_000;});await expired.goto('http://127.0.0.1:4320/caja');await expired.getByLabel('Usuario',{exact:true}).fill('e2e-owner');await expired.getByLabel('Contraseña',{exact:true}).fill(password);await expired.getByRole('button',{name:'Entrar a caja'}).click();await expect(expired.getByText('Han pasado siete días. Inicia sesión online para volver a cobrar.',{exact:true})).toBeVisible();await expired.getByRole('navigation').getByRole('button',{name:'Turno',exact:true}).click();await expect(expired.getByRole('button',{name:'Cerrar turno',exact:true})).toBeEnabled();await expired.close();
  const cached=await page.evaluate(async()=>{const names=await caches.keys();const urls=[];for(const n of names)for(const r of await (await caches.open(n)).keys())urls.push(r.url);return urls;});expect(cached.some(u=>u.includes('/api/'))).toBeFalsy();
 }finally{await context.close();}
}
