import { expect } from '@playwright/test';
import type { Page } from '@playwright/test';
import { AxeBuilder } from '@axe-core/playwright';
import { mkdir } from 'node:fs/promises';
export async function exerciseLoyalty(page:Page){
 const root='docs/evidence/unified-web';await mkdir(root,{recursive:true});const dialog=page.getByRole('dialog');await page.keyboard.press('Escape');await page.setViewportSize({width:1440,height:1000});
 await page.getByRole('navigation').getByRole('button',{name:'Fidelización',exact:true}).click();await expect(page.getByRole('heading',{name:'Fidelización',exact:true})).toBeVisible();await page.getByRole('button',{name:'Inscribir · Cliente E2E',exact:true}).click();await expect(page.getByText('0 puntos',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Ajustar puntos · Cliente E2E',exact:true}).click();await expect(dialog.getByLabel('Puntos a sumar o restar')).toBeFocused();await dialog.getByLabel('Puntos a sumar o restar').fill('100');await dialog.getByLabel('Motivo del cambio').fill('Saldo sintético de aceptación');await dialog.getByRole('button',{name:'Registrar ajuste'}).click();await expect(dialog).not.toBeVisible();await expect(page.getByText('100 puntos',{exact:true})).toBeVisible();
 for(const view of [{width:1440,height:1000,name:'desktop'},{width:390,height:844,name:'mobile'}]){await page.setViewportSize(view);for(const dark of [false,true]){const toggle=page.getByRole('switch',{name:'Modo oscuro'});if((await toggle.getAttribute('aria-checked')==='true')!==dark)await toggle.click();const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(axe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:`${root}/${view.name}-${dark?'dark':'light'}-loyalty.png`,fullPage:true});}}
 await page.setViewportSize({width:1440,height:1000});await page.goto('http://127.0.0.1:4320/caja');await expect(page.getByRole('heading',{name:'Nueva venta'})).toBeVisible();await page.getByRole('button',{name:'Sincronizar',exact:true}).click();await expect(page.locator('.pos-sync')).toContainText('0 pendientes');await page.getByRole('button',{name:'Cobrar pedido',exact:true}).click();await expect(dialog).toContainText('100 puntos');await dialog.getByLabel('Puntos a canjear').fill('100');await dialog.getByLabel('Importe 1 (COP)').fill('11600');await expect(dialog).toContainText('11.600');await expect(dialog).toContainText('Puntos de esta compra: 11');const checkoutAxe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(checkoutAxe.violations.map(v=>v.id)).toEqual([]);await page.screenshot({path:`${root}/desktop-redemption.png`,fullPage:true});await dialog.getByRole('button',{name:'Confirmar cobro'}).click();await expect(dialog.getByRole('heading',{name:'Comprobante interno'})).toBeVisible();await expect(dialog).toContainText('Puntos de esta compra: 11');await expect(dialog).toContainText('Confirmados');await page.screenshot({path:`${root}/desktop-points-receipt.png`,fullPage:true});await page.keyboard.press('Escape');
 await page.getByRole('navigation').getByRole('button',{name:'Comprobantes',exact:true}).click();await page.getByRole('button',{name:'Devolver',exact:true}).first().click();await dialog.getByLabel('Devolver · Batido de prueba').fill('1');await expect(dialog).toContainText('Puntos a restituir: 100');await expect(dialog).toContainText('Puntos generados a revertir: 11');await dialog.getByRole('button',{name:'Devolver total en efectivo'}).click();await dialog.getByLabel('Motivo de devolución').fill('Devolución sintética con puntos');await page.setViewportSize({width:390,height:844});await page.screenshot({path:`${root}/mobile-points-refund.png`,fullPage:true});await dialog.getByRole('button',{name:'Confirmar devolución'}).click();await expect(dialog).not.toBeVisible();await page.getByRole('button',{name:'Sincronizar',exact:true}).click();await expect(page.locator('.pos-sync')).toContainText('0 pendientes');
 await page.goto('http://127.0.0.1:4320/');await page.setViewportSize({width:1440,height:1000});await page.getByLabel('Sucursal',{exact:true}).selectOption('centro');await page.getByRole('navigation').getByRole('button',{name:'Fidelización',exact:true}).click();await expect(page.getByText('100 puntos',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Historia de puntos · Cliente E2E',exact:true}).click();await expect(dialog).toContainText('89 puntos');await expect(dialog).toContainText('-89 puntos');await page.screenshot({path:`${root}/desktop-points-history.png`,fullPage:true});await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Cambiar reglas',exact:true}).click();await dialog.getByLabel('Productos pagados por punto (COP)').fill('500');await dialog.getByLabel('Motivo del cambio').fill('Nueva versión sintética');await dialog.getByRole('button',{name:'Guardar nueva regla'}).click();await expect(dialog).not.toBeVisible();await expect(page.locator('.loyalty-overview')).toContainText('500');
}
