import { exerciseCajaUi } from './caja-ui-flow.ts';
import { expect } from '@playwright/test';
import type { Page } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { AxeBuilder } from '@axe-core/playwright';
export async function exercisePos(page: Page, password: string) {
  const nav = async (name:string) => { if(!await page.getByRole('navigation').isVisible()) await page.getByRole('button',{name:'Menú de Caja',exact:true}).click(); await page.getByRole('navigation').getByRole('button',{name,exact:true}).click(); };
  const root = 'test-results/unified-web/regression'; await mkdir(root, { recursive: true });
  await page.setViewportSize({ width: 1440, height: 1000 }); await page.goto('http://127.0.0.1:4320/caja');
  
  await expect(page.getByRole('heading', { name: 'Activa esta caja' })).toBeVisible();
  const device = await page.getByLabel('Equipo', { exact: true }).locator('option').evaluateAll(options => options.find(o => o.textContent?.startsWith('Centro'))?.getAttribute('value'));
  expect(device).toBeTruthy(); await page.getByLabel('Equipo', { exact: true }).selectOption(device!); await page.getByRole('button', { name: 'Activar caja' }).click();
  await expect(page.getByRole('heading', { name: 'Nueva venta' })).toBeVisible(); await page.getByRole('button', { name: 'Abrir turno', exact: true }).click();
  const dialog = page.getByRole('dialog'); await expect(dialog.getByLabel('Base de efectivo (COP)')).toBeFocused(); await dialog.getByLabel('Base de efectivo (COP)').fill('50000'); await dialog.getByRole('button', { name: 'Confirmar apertura' }).click(); await expect(dialog).not.toBeVisible();
  await nav('Turno'); await page.getByRole('button', { name: 'Registrar ingreso o salida', exact: true }).click(); await dialog.getByLabel('Clase').selectOption('expense'); await dialog.getByLabel('Importe (COP)').fill('1000'); await dialog.getByLabel('Motivo').fill('Gasto sintético E2E'); await dialog.getByRole('button', { name: 'Registrar movimiento' }).click(); await expect(dialog).not.toBeVisible(); await expect(page.locator('.pos-shift')).toContainText('Gasto sintético E2E'); await expect(page.locator('.pos-shift')).toContainText('49.000'); await nav('Venta');
  await page.getByRole('button').filter({ hasText: 'Batido de prueba' }).click(); await dialog.getByLabel('Cantidad', { exact: true }).fill('2'); await dialog.getByLabel(/Leche adicional/).check(); await dialog.getByRole('button', { name: 'Guardar en pedido' }).click(); await expect(dialog).not.toBeVisible();
  await page.reload(); await expect(page.getByRole('region', { name: 'Pedido' })).toContainText('2 × Batido de prueba');
  await exerciseCajaUi(page);
  for (const viewport of [{ width: 1440, height: 1000, name: 'desktop' }, { width: 390, height: 844, name: 'mobile' }]) {
    await page.setViewportSize(viewport);
    for (const dark of [false, true]) {
      const toggle = page.getByRole('switch', { name: 'Modo oscuro' }); if ((await toggle.getAttribute('aria-checked') === 'true') !== dark) await toggle.click();
      const report = await new AxeBuilder({ page }).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze(); expect(report.violations.map(v => ({ id: v.id, nodes: v.nodes.map(n => n.target) }))).toEqual([]);
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
      await page.screenshot({ path: `${root}/${viewport.name}-${dark ? 'dark' : 'light'}-sale.png`, fullPage: true });
    }
  }
  await page.getByRole('button', { name: 'Cobrar', exact: true }).click();
  await expect(dialog.getByLabel('Buscar cliente', { exact: true })).toBeFocused(); await dialog.getByLabel('Importe 1 (COP)').fill('10000'); await dialog.getByRole('button', { name: 'Confirmar cobro' }).click(); await expect(dialog.getByRole('alert')).toContainText('insuficiente');
  await dialog.getByLabel('Importe 1 (COP)').fill('30000'); await dialog.getByRole('button', { name: 'Confirmar cobro' }).click(); await expect(dialog.getByRole('heading', { name: 'Comprobante interno' })).toBeVisible(); await expect(dialog).toContainText('28.000'); await expect(dialog).toContainText('2.000'); await expect(dialog).toContainText('Sin impuesto asignado');
  const report = await new AxeBuilder({ page }).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze(); expect(report.violations.map(v => v.id)).toEqual([]);
  await page.screenshot({ path: `${root}/mobile-receipt.png`, fullPage: true }); await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Sincronizar', exact: true }).click(); await expect(page.locator('.pos-sync')).toContainText('0 pendientes');
  await nav('Comprobantes'); await expect(page.getByRole('button', { name: 'Ver copia' })).toHaveCount(1); await page.getByRole('button', { name: 'Ver copia' }).click(); await expect(dialog).toContainText('28.000'); await page.keyboard.press('Escape');
  await nav('Turno'); await expect(page.locator('.pos-shift')).toContainText('77.000'); await page.getByRole('button', { name: 'Cerrar turno' }).click(); await dialog.getByLabel('Efectivo contado (COP)').fill('77500'); await dialog.getByRole('button', { name: 'Confirmar cierre' }).click(); await expect(dialog).not.toBeVisible(); await expect(page.locator('.pos-shift')).toContainText('No hay un turno abierto');
  await page.getByRole('button', { name: 'Sincronizar', exact: true }).click(); await expect(page.locator('.pos-sync')).toContainText('0 pendientes');
  const other=await page.context().newPage();await other.goto('http://127.0.0.1:4320/caja');await expect(other.getByRole('heading',{name:'Nueva venta'})).toBeVisible();await other.getByRole('navigation').getByRole('button',{name:'Comprobantes',exact:true}).click();await expect(other.getByRole('button',{name:'Ver copia'})).toHaveCount(1);await other.close();

  await page.setViewportSize({width:1440,height:1000});
  await nav('Venta');
  await page.getByRole('button',{name:'Abrir turno',exact:true}).click();await dialog.getByLabel('Base de efectivo (COP)').fill('50000');await dialog.getByRole('button',{name:'Confirmar apertura'}).click();await expect(dialog).not.toBeVisible();
  const virtualOrder=page.getByRole('tab',{selected:true});const virtualOrderId=await virtualOrder.getAttribute('data-order-id');
  await virtualOrder.locator('..').getByRole('button',{name:/Cerrar/}).click();await expect(dialog).not.toBeVisible();
  await expect(page.locator(`[role="tab"][data-order-id="${virtualOrderId}"]`)).toHaveCount(0);
  const freshOrder=page.getByRole('tab',{selected:true});await freshOrder.locator('..').getByRole('button',{name:/Cambiar nombre/}).click();
  await dialog.getByLabel('Nombre de la pestaña').fill('Venta mostrador E2E');await dialog.getByRole('button',{name:'Guardar nombre',exact:true}).click();await expect(dialog).not.toBeVisible();
  await expect(page.getByRole('tab',{name:'Venta mostrador E2E',exact:true})).toHaveAttribute('aria-selected','true');
  await page.getByRole('button',{name:'+ Nuevo cliente',exact:true}).click();await dialog.getByLabel('Nombre del cliente').fill('Cliente E2E');await dialog.getByLabel('Documento',{exact:true}).fill('E2E-CLIENT');await dialog.getByLabel('Celular').fill('3000000000');await dialog.getByRole('button',{name:'Guardar y seleccionar cliente'}).click();await expect(dialog).not.toBeVisible();
  await page.getByRole('button',{name:'Datos del pedido'}).click();await dialog.getByLabel('Atención').selectOption('delivery');await dialog.getByLabel('Dirección del domicilio').fill('Dirección sintética');await dialog.getByLabel('Envío pendiente (COP)').fill('3000');await dialog.getByLabel('Nombre del pedido').fill('Domicilio E2E');await dialog.getByRole('button',{name:'Guardar pedido',exact:true}).click();await expect(dialog).not.toBeVisible();
  await page.getByRole('button').filter({hasText:'Batido de prueba'}).click();await dialog.getByLabel('Cantidad',{exact:true}).fill('3');await dialog.getByLabel(/Leche adicional/).check();await dialog.getByLabel('Tipo de descuento').selectOption('percent');await dialog.getByLabel('Descuento',{exact:true}).fill('10');await dialog.getByLabel('Notas de preparación').fill('Sin hielo · prueba');await dialog.getByRole('button',{name:'Guardar en pedido'}).click();await expect(dialog).not.toBeVisible();
  await page.getByRole('button',{name:'Enviar a preparación'}).click();await expect(page.getByRole('region',{name:'Pedido'})).toContainText('Enviadas: 3');
  await page.getByRole('button',{name:'+ Nuevo pedido',exact:true}).click();await expect(page.getByRole('region',{name:'Pedido'})).toContainText('Agrega un producto');await page.getByRole('button',{name:'Datos del pedido'}).click();await dialog.getByLabel('Atención').selectOption('table');await dialog.getByLabel('Mesa',{exact:true}).fill('Mesa 2');await dialog.getByRole('button',{name:'Guardar pedido',exact:true}).click();await expect(dialog).not.toBeVisible();
  await page.getByRole('tab',{name:'Domicilio E2E',exact:true}).click();await expect(page.getByRole('region',{name:'Pedido'})).toContainText('3 × Batido');
  await page.getByRole('button',{name:'Quitar Batido de prueba',exact:true}).click();await dialog.getByLabel('Unidades a cancelar').fill('1');await dialog.getByLabel('De estas, ya preparadas').fill('1');await dialog.getByLabel('Motivo',{exact:true}).fill('Unidad preparada cancelada');await dialog.getByRole('button',{name:'Confirmar cancelación'}).click();await expect(dialog).not.toBeVisible();await expect(page.getByRole('region',{name:'Pedido'})).toContainText('2 × Batido');
  await page.getByRole('button',{name:'Cobrar pedido',exact:true}).click();await dialog.getByRole('button',{name:'Dividir cuenta',exact:true}).click();await dialog.getByLabel(/Cantidad a cobrar/).fill('1');await dialog.getByLabel('Tipo de propina').selectOption('percent');await dialog.getByLabel('Propina voluntaria').fill('10');await dialog.getByLabel('Envío a cobrar (COP)').fill('3000');await dialog.getByLabel('Importe 1 (COP)').fill('10000');await dialog.getByRole('button',{name:'+ Agregar medio de pago'}).click();await dialog.getByLabel('Medio de pago 2').selectOption('nequi');await dialog.getByLabel('Importe 2 (COP)').fill('10000');
  await page.screenshot({path:`${root}/desktop-split-payment.png`,fullPage:true});await dialog.getByRole('button',{name:'Confirmar cobro'}).click();await expect(dialog.getByRole('heading',{name:'Comprobante interno'})).toBeVisible();await expect(dialog).toContainText('16.860');await expect(dialog).toContainText('Cliente E2E');await expect(dialog).toContainText('3.140');await page.screenshot({path:`${root}/desktop-split-receipt.png`,fullPage:true});await page.keyboard.press('Escape');await expect(page.getByRole('region',{name:'Pedido'})).toContainText('1 × Batido');
  await page.reload();await expect(page.getByRole('region',{name:'Pedido'})).toContainText('1 × Batido');await nav('Comandas');await expect(page.locator('#pos-main')).toContainText('Sin hielo');await page.screenshot({path:`${root}/desktop-comanda.png`,fullPage:true});
  await nav('Comprobantes');await page.getByRole('button',{name:'Devolver',exact:true}).first().click();await dialog.getByLabel('Propina a devolver (COP)').fill('1260');await dialog.getByLabel('Domicilio a devolver (COP)').fill('1000');await dialog.getByRole('button',{name:'Devolver total en efectivo'}).click();await dialog.getByLabel('Motivo de devolución').fill('Propina y domicilio devueltos');await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();const refundsAxe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(refundsAxe.violations.map(v=>v.id)).toEqual([]);await page.screenshot({path:`${root}/mobile-refund.png`,fullPage:true});await dialog.getByRole('button',{name:'Confirmar devolución'}).click();await expect(dialog).not.toBeVisible();await expect(page.locator('#pos-main')).toContainText('Devoluciones registradas');
  await page.getByRole('button',{name:'Sincronizar',exact:true}).click();await expect(page.locator('.pos-sync')).toContainText('0 pendientes');await nav('Turno');await expect(page.locator('.pos-shift')).toContainText('54.600');await expect(page.locator('.pos-shift')).toContainText('Domicilio neto');await page.screenshot({path:`${root}/mobile-shift.png`,fullPage:true});
  await page.goto('http://127.0.0.1:4320/');await page.setViewportSize({width:1440,height:1000});await page.getByLabel('Sucursal',{exact:true}).selectOption('centro');await nav('Clientes');await page.getByRole('button',{name:'Ver historia de Cliente E2E'}).click();await expect(dialog).toContainText('16.860');await expect(dialog).toContainText('Devolución');await page.screenshot({path:`${root}/desktop-customer-history.png`,fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();const customerAxe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(customerAxe.violations.map(v=>v.id)).toEqual([]);await page.screenshot({path:`${root}/mobile-customer-history.png`,fullPage:true});

}
