import test from 'node:test';
import assert from 'node:assert/strict';
import { randomBytes, randomUUID } from 'node:crypto';
import { resolve } from 'node:path';
import { startLocalPostgres } from '../../scripts/local-postgres.ts';
import { migrate } from '../../src/server/db.ts';
import { createApp } from '../../src/server/app.ts';

test('AC-010-01/02/03/04 — agente limitado, importación atómica y revocación', { timeout: 120_000 }, async () => {
  const db = await startLocalPostgres(resolve('.local/agent-api-test-' + randomUUID()), { password: randomBytes(32).toString('hex') });
  const app = await createApp({ pool: db.pool, origin: 'http://127.0.0.1:4370' });
  try {
    await migrate(db.pool);
    const password = randomBytes(24).toString('base64url');
    const setup = await app.inject({ method: 'POST', url: '/api/setup', payload: { name: 'Dueño agentes', login: 'owner-agents', password }, headers: { host: '127.0.0.1:4370', 'x-nativos-request': '1' } });
    assert.equal(setup.statusCode, 201, setup.body);
    const headers = { host: '127.0.0.1:4370', cookie: `nativos_session=${setup.cookies[0]!.value}`, 'x-nativos-request': '1' };
    const created = await app.inject({ method: 'POST', url: '/api/agents', payload: { name: 'Consulta Centro', branchIds: ['centro'], actions: ['data.read', 'inventory.manage', 'product.create', 'recipe.create'], reason: 'Consulta de inventario autorizada' }, headers });
    assert.equal(created.statusCode, 201, created.body);
    const agent = created.json() as { id: string; token: string; branchIds: string[]; actions: string[] };
    assert.match(agent.token, /^[A-Za-z0-9_-]{43}$/);
    assert.deepEqual(agent.branchIds, ['centro']);
    assert.deepEqual(agent.actions, ['data.read', 'inventory.manage', 'product.create', 'recipe.create']);
    assert.doesNotMatch(String((await db.pool.query('SELECT token_hash FROM agent_credentials WHERE user_id=$1', [agent.id])).rows[0].token_hash), new RegExp(agent.token));
    const me = await app.inject({ method: 'GET', url: '/api/agent/v1/me', headers: { host: '127.0.0.1:4370', authorization: `Bearer ${agent.token}` } });
    assert.equal(me.statusCode, 200, me.body);
    assert.deepEqual(me.json(), { id: agent.id, name: 'Consulta Centro', branchIds: ['centro'], actions: ['data.read', 'inventory.manage', 'product.create', 'recipe.create'] });
    await db.pool.query("INSERT INTO inventory_items(id,name,reference,kind,base_unit) VALUES('agent-item','Artículo agente','agent-item','raw','unit')");
    await db.pool.query("INSERT INTO inventory_items(id,name,reference,kind,base_unit) VALUES('agent-initial-item','Artículo inicial','agent-initial-item','raw','unit')");
    await db.pool.query("INSERT INTO inventory_minimums(warehouse_id,item_id,minimum) VALUES('centro-venta','agent-item','5')");
    await db.pool.query("INSERT INTO inventory_movements(id,item_id,warehouse_id,kind,quantity,reason) VALUES('agent-initial','agent-item','centro-venta','initial','7','Inicial sintético')");
    const inventory = await app.inject({ method: 'GET', url: '/api/agent/v1/inventory?branchId=centro', headers: { host: '127.0.0.1:4370', authorization: `Bearer ${agent.token}` } });
    assert.equal(inventory.statusCode, 200, inventory.body);
    assert.deepEqual(inventory.json().items.find((item: { itemId: string }) => item.itemId === 'agent-item'), { id: 'centro-venta:agent-item', warehouseId: 'centro-venta', warehouse: 'Bodega de venta', itemId: 'agent-item', name: 'Artículo agente', reference: 'agent-item', baseUnit: 'unit', quantity: '7.000000', minimum: '5.000000' });
    const movements = await app.inject({ method: 'GET', url: '/api/agent/v1/movements?branchId=centro', headers: { host: '127.0.0.1:4370', authorization: `Bearer ${agent.token}` } });
    assert.equal(movements.statusCode, 200, movements.body);
    assert.equal(movements.json().items[0].id, 'agent-initial');
    assert.doesNotMatch(movements.body, /unit_cost|entry/i);
    const report = await app.inject({ method: 'GET', url: '/api/agent/v1/reports/inventory?branchId=centro', headers: { host: '127.0.0.1:4370', authorization: `Bearer ${agent.token}` } });
    assert.equal(report.statusCode, 200, report.body);
    assert.equal(report.json().context.lastSynchronizedAt.centro, null);
    const otherBranch = await app.inject({ method: 'GET', url: '/api/agent/v1/reports/inventory?branchId=milan', headers: { host: '127.0.0.1:4370', authorization: `Bearer ${agent.token}` } });
    assert.equal(otherBranch.statusCode, 403, otherBranch.body);
    const importDraft = { kind: 'inventory', operationId: randomUUID(), branchId: 'centro', reason: 'Carga desde archivo validado', rows: [{ row: 2, kind: 'entry', itemId: 'agent-item', warehouseId: 'centro-venta', quantity: '3', unit: 'unit', reason: 'Entrada del archivo' }, { row: 3, kind: 'initial', itemId: 'agent-initial-item', warehouseId: 'centro-venta', quantity: '4', unit: 'unit', reason: 'Inicial del archivo' }, { row: 4, kind: 'adjustment_out', itemId: 'agent-item', warehouseId: 'centro-venta', quantity: '2', unit: 'unit', reason: 'Ajuste del archivo' }] };
    const agentHeaders = { host: '127.0.0.1:4370', authorization: `Bearer ${agent.token}`, 'x-nativos-request': '1' };
    const preview = await app.inject({ method: 'POST', url: '/api/agent/v1/imports/preview', payload: importDraft, headers: agentHeaders });
    assert.equal(preview.statusCode, 200, preview.body); assert.equal(preview.json().valid, true);
    const confirmed = await app.inject({ method: 'POST', url: '/api/agent/v1/imports/confirm', payload: { ...importDraft, previewFingerprint: preview.json().previewFingerprint }, headers: agentHeaders });
    assert.equal(confirmed.statusCode, 200, confirmed.body); assert.deepEqual((await db.pool.query("SELECT kind,quantity::text FROM inventory_movements WHERE agent_import_id=$1 ORDER BY kind", [confirmed.json().importId])).rows, [{ kind: 'import_adjustment_out', quantity: '-2.000000' }, { kind: 'import_entry', quantity: '3.000000' }, { kind: 'import_initial', quantity: '4.000000' }]);
    const retried = await app.inject({ method: 'POST', url: '/api/agent/v1/imports/confirm', payload: { ...importDraft, previewFingerprint: preview.json().previewFingerprint }, headers: agentHeaders });
    assert.equal(retried.statusCode, 200, retried.body); assert.deepEqual(retried.json(), confirmed.json());
    const invalidPreview = await app.inject({ method: 'POST', url: '/api/agent/v1/imports/preview', payload: { ...importDraft, operationId: randomUUID(), rows: [{ ...importDraft.rows[0], unit: 'arroba' }] }, headers: agentHeaders });
    assert.equal(invalidPreview.statusCode, 200, invalidPreview.body); assert.equal(invalidPreview.json().valid, false); assert.deepEqual(invalidPreview.json().errors, [{ row: 2, field: 'unit', code: 'invalid_unit', message: 'La unidad no es válida para el artículo.' }]); assert.equal((await db.pool.query('SELECT count(*) FROM agent_inventory_imports')).rows[0].count, '1');
    const changedPreview = await app.inject({ method: 'POST', url: '/api/agent/v1/imports/preview', payload: { ...importDraft, rows: [{ ...importDraft.rows[0], quantity: '5' }] }, headers: agentHeaders });
    assert.equal(changedPreview.statusCode, 200, changedPreview.body); assert.equal(changedPreview.json().valid, true);
    const conflict = await app.inject({ method: 'POST', url: '/api/agent/v1/imports/confirm', payload: { ...importDraft, rows: [{ ...importDraft.rows[0], quantity: '5' }], previewFingerprint: changedPreview.json().previewFingerprint }, headers: agentHeaders });
    assert.equal(conflict.statusCode, 409, conflict.body);
    const catalogDraft = { kind: 'catalog', operationId: randomUUID(), branchId: 'centro', reason: 'Alta inicial desde catálogo autorizado', rows: [
      { row: 2, product: { name: 'Galleta terminada', reference: 'agent-finished', category: 'Panadería', presentation: 'Unidad', type: 'finished', price: '4.5', tax: null, description: 'Venta directa' }, recipe: null },
      { row: 3, product: { name: 'Bebida preparada', reference: 'agent-prepared', category: 'Bebidas', presentation: 'Vaso', type: 'prepared', price: '8', tax: { label: 'IVA', rate: '19', exempt: false }, description: 'Preparada al momento' }, recipe: { name: 'Bebida base', instructions: 'Mezclar.', lines: [{ id: 'base', itemId: 'agent-item', quantity: '1', unit: 'unit', conversion: null, kind: 'ingredient' }], options: [] } }
    ] };
    const catalogPreview = await app.inject({ method: 'POST', url: '/api/agent/v1/imports/catalog/preview', payload: catalogDraft, headers: agentHeaders });
    assert.equal(catalogPreview.statusCode, 200, catalogPreview.body); assert.equal(catalogPreview.json().valid, true, catalogPreview.body);
    const catalogConfirmed = await app.inject({ method: 'POST', url: '/api/agent/v1/imports/catalog/confirm', payload: { ...catalogDraft, previewFingerprint: catalogPreview.json().previewFingerprint }, headers: agentHeaders });
    assert.equal(catalogConfirmed.statusCode, 200, catalogConfirmed.body); assert.equal(catalogConfirmed.json().products.length, 2);
    const catalogRetry = await app.inject({ method: 'POST', url: '/api/agent/v1/imports/catalog/confirm', payload: { ...catalogDraft, previewFingerprint: catalogPreview.json().previewFingerprint }, headers: agentHeaders });
    assert.deepEqual(catalogRetry.json(), catalogConfirmed.json());
    const catalogRows = catalogConfirmed.json().products as { productId: string; recipeId: string | null }[];
    assert.equal((await db.pool.query('SELECT count(*) FROM agent_catalog_imports')).rows[0].count, '1');
    assert.equal((await db.pool.query('SELECT count(*) FROM inventory_items WHERE id=$1', [catalogRows[0]!.productId])).rows[0].count, '1');
    assert.equal((await db.pool.query('SELECT count(*) FROM recipe_versions WHERE id=$1', [catalogRows[1]!.recipeId])).rows[0].count, '1');
    const invalidCatalog = await app.inject({ method: 'POST', url: '/api/agent/v1/imports/catalog/preview', payload: { ...catalogDraft, operationId: randomUUID(), rows: [{ ...catalogDraft.rows[0]!, product: { ...catalogDraft.rows[0]!.product, reference: 'duplicate-reference' } }, { ...catalogDraft.rows[0]!, row: 4, product: { ...catalogDraft.rows[0]!.product, reference: 'duplicate-reference' } }] }, headers: agentHeaders });
    assert.equal(invalidCatalog.statusCode, 200, invalidCatalog.body); assert.equal(invalidCatalog.json().valid, false); assert.equal((await db.pool.query('SELECT count(*) FROM catalog_products WHERE reference=$1', ['duplicate-reference'])).rows[0].count, '0');
    const mcpList = await app.inject({ method: 'POST', url: '/api/agent/v1/mcp', payload: { jsonrpc: '2.0', id: 1, method: 'tools/list' }, headers: agentHeaders });
    assert.equal(mcpList.statusCode, 200, mcpList.body); assert.ok(mcpList.json().result.tools.some((tool: { name: string }) => tool.name === 'nativos_catalog_import_confirm'));
    const mcpProducts = await app.inject({ method: 'POST', url: '/api/agent/v1/mcp', payload: { jsonrpc: '2.0', id: 2, method: 'tools/call', params: { name: 'nativos_products_list', arguments: { branchId: 'centro' } } }, headers: agentHeaders });
    assert.equal(mcpProducts.statusCode, 200, mcpProducts.body); assert.equal(mcpProducts.json().result.isError, undefined); assert.ok(JSON.parse(mcpProducts.json().result.content[0].text).items.length >= 2);
    const readOnly = await app.inject({ method: 'POST', url: '/api/agents', payload: { name: 'Sólo lectura MCP', branchIds: ['centro'], actions: ['data.read'], reason: 'Prueba de límite MCP' }, headers });
    assert.equal(readOnly.statusCode, 201, readOnly.body);
    const deniedMcp = await app.inject({ method: 'POST', url: '/api/agent/v1/mcp', payload: { jsonrpc: '2.0', id: 3, method: 'tools/call', params: { name: 'nativos_inventory_import_preview', arguments: importDraft } }, headers: { host: '127.0.0.1:4370', authorization: `Bearer ${readOnly.json().token}`, 'x-nativos-request': '1' } });
    assert.equal(deniedMcp.statusCode, 200, deniedMcp.body); assert.equal(deniedMcp.json().result.isError, true); assert.match(deniedMcp.json().result.content[0].text, /forbidden/);
    const rotated = await app.inject({ method: 'POST', url: `/api/agents/${agent.id}/rotate`, payload: { reason: 'Rotación programada de credencial' }, headers });
    assert.equal(rotated.statusCode, 200, rotated.body);
    const replacement = rotated.json().token as string;
    assert.match(replacement, /^[A-Za-z0-9_-]{43}$/);
    assert.notEqual(replacement, agent.token);
    const oldToken = await app.inject({ method: 'GET', url: '/api/agent/v1/me', headers: { host: '127.0.0.1:4370', authorization: `Bearer ${agent.token}` } });
    assert.equal(oldToken.statusCode, 401, oldToken.body);
    const newToken = await app.inject({ method: 'GET', url: '/api/agent/v1/me', headers: { host: '127.0.0.1:4370', authorization: `Bearer ${replacement}` } });
    assert.equal(newToken.statusCode, 200, newToken.body);
    const normalLogin = await app.inject({ method: 'POST', url: '/api/login', payload: { login: `agent-${agent.id}`, password }, headers: { host: '127.0.0.1:4370', 'x-nativos-request': '1' } });
    assert.equal(normalLogin.statusCode, 401, normalLogin.body);
    const revoked = await app.inject({ method: 'PATCH', url: `/api/agents/${agent.id}`, payload: { active: false, reason: 'Fin de la consulta autorizada' }, headers });
    assert.equal(revoked.statusCode, 200, revoked.body);
    const rejected = await app.inject({ method: 'GET', url: '/api/agent/v1/me', headers: { host: '127.0.0.1:4370', authorization: `Bearer ${replacement}` } });
    assert.equal(rejected.statusCode, 401, rejected.body);
    assert.equal((await db.pool.query("SELECT count(*) FROM audit_events WHERE action IN ('agent.created','agent.rotated','agent.revoked')")).rows[0].count, '4');
  } finally { await app.close(); await db.stop(); }
});
