import { useEffect, useRef, useState } from 'react';
import { api } from './api.ts';
import { Heading, Notice, Dialog } from './components.tsx';
import { CustomerForm, money, when } from './OrderForms.tsx';
import type { Customer, SaleV2, RefundV2 } from '../src/orders-domain.ts';
type History = {sale:SaleV2;refunds:RefundV2[]};
export function Customers({branchId}:{branchId:string}) {
  const [items,setItems]=useState<Customer[]>([]),[q,setQ]=useState(''),[error,setError]=useState(''),[creating,setCreating]=useState(false),[selected,setSelected]=useState<Customer|null>(null),[history,setHistory]=useState<History[]>([]),[loading,setLoading]=useState(false);
  const operation=useRef({key:'',id:''});
  useEffect(()=>{let active=true;setLoading(true);setError('');void (async()=>{let after:string|null=null;const all:Customer[]=[];do{const r: {items:Customer[];nextCursor:string|null}=await api('/customers?branchId='+encodeURIComponent(branchId)+(after?'&after='+encodeURIComponent(after):''));all.push(...r.items);after=r.nextCursor;}while(after);if(active)setItems(all);})().catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[branchId,creating]);
  async function show(customer:Customer){setError('');setLoading(true);try{const all:History[]=[];let after:string|null=null;do{const r:{items:History[];nextCursor:string|null}=await api(`/customers/${customer.id}/history?branchId=${encodeURIComponent(branchId)}`+(after?'&after='+encodeURIComponent(after):''));all.push(...r.items);after=r.nextCursor;}while(after);setHistory(all.sort((a,b)=>b.sale.occurredAtMs-a.sale.occurredAtMs));setSelected(customer);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
  return <><Heading eyebrow="RELACIÓN CON CLIENTES" title="Clientes" action={<button className="primary" onClick={()=>setCreating(true)}>+ Nuevo cliente</button>}>Directorio compartido. La historia muestra únicamente cobros sincronizados de la sucursal seleccionada.</Heading>{error&&<Notice error>{error}</Notice>}<section className="panel"><div className="panel-toolbar"><label>Buscar cliente<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nombre, documento o celular"/></label></div>{loading&&<p role="status">Consultando registros…</p>}{items.filter(c=>(c.name+' '+c.document+' '+c.phone).toLowerCase().includes(q.toLowerCase())).map(c=><article className="catalog-row" key={c.id}><div><h2>{c.name}</h2><p>{c.document} · {c.phone}</p></div><button className="secondary" disabled={loading} onClick={()=>void show(c)}>Ver historia de {c.name}</button></article>)}{!items.length&&!loading&&<p className="empty">Aún no hay clientes registrados. La caja conserva Consumidor final.</p>}</section>{creating&&<CustomerForm close={()=>setCreating(false)} save={async body=>{const key=JSON.stringify(body);if(operation.current.key!==key)operation.current={key,id:crypto.randomUUID()};await api('/customers','POST',{...body,branchId,operationId:operation.current.id});operation.current={key:'',id:''};setCreating(false);}}/>}{selected&&<Dialog title={'Historia de '+selected.name} onClose={()=>setSelected(null)}><p>{selected.document} · {selected.phone}<br/>{selected.email}<br/>{selected.address}</p><Notice>Cobros sincronizados de {branchId==='milan'?'Milán':'Centro'}. Los pendientes de caja aparecerán después de sincronizar.</Notice>{!history.length&&<p>No hay cobros sincronizados para este cliente en esta sucursal.</p>}{history.map(({sale,refunds})=><article className="catalog-row customer-history" key={sale.id}><div><strong>{money(sale.total)}</strong><p>{when(sale.occurredAtMs)} · {sale.actorName}</p><small>{sale.receiptNumber}</small><p>Productos {money(sale.products)} · Propina {money(sale.tip)} · Domicilio {money(sale.shipping)}</p>{refunds.map(r=><p key={r.id}>Devolución {money(r.total)} · {r.reason}</p>)}</div></article>)}</Dialog>}</>;
}
