import { useEffect, useRef, useState } from 'react';
import { api } from './api.ts';
import type { BranchDetail, Me, Warehouse } from './api.ts';
import type { Item } from '../src/catalog.ts';
import { allPages } from './Catalog.tsx';
import { Dialog, Heading, Notice, Reason, SaveForm } from './components.tsx';

type Transfer = { id: string; sourceWarehouseId: string; targetWarehouseId: string; dispatched: boolean; requestedQuantity: string; receivedQuantity: string; createdAt: string };
type TransferDetail = Transfer & { lines: { id: string; itemId: string; baseQuantity: string; receivedQuantity: string }[] };
type Line = { id: string; itemId: string; quantity: string; unit: string };
type WarehouseChoice = Warehouse & { branchName: string };
const newLine = (): Line => ({ id: crypto.randomUUID(), itemId: '', quantity: '', unit: '' });
function useOperation(branchId: string) { const last = useRef({ payload: '', id: '' }); return async (url: string, body: object) => { const payload = JSON.stringify({ url, branchId, ...body }); if (last.current.payload !== payload) last.current = { payload, id: crypto.randomUUID() }; return api(url, 'POST', { ...body, branchId, operationId: last.current.id }); }; }
const value = (d: FormData, name: string) => String(d.get(name) ?? '');
const qty = (n: string) => n.replace(/\.0+$/, '');

export function Transfers({ me, branchId }: { me: Me; branchId: string }) {
  const [warehouses, setWarehouses] = useState<WarehouseChoice[]>([]); const [items, setItems] = useState<Item[]>([]); const [transfers, setTransfers] = useState<Transfer[]>([]); const [error, setError] = useState(''); const [dialog, setDialog] = useState<'new' | TransferDetail | null>(null);
  const canWrite = me.user.actions.includes('inventory.manage');
  async function refresh() { try { const [details, i, t] = await Promise.all([Promise.all(me.branches.map(branch => api<BranchDetail>(`/branches/${branch.id}`))), allPages<Item>(`/items?branchId=${branchId}`), allPages<Transfer>(`/transfers?branchId=${branchId}`)]); setWarehouses(details.flatMap(detail => detail.warehouses.map(warehouse => ({ ...warehouse, branchName: detail.branch.name })))); setItems(i.filter(i => i.kind !== 'finished')); setTransfers(t); setError(''); } catch (e) { setError((e as Error).message); } }
  useEffect(() => { void refresh(); }, [branchId]);
  async function open(t: Transfer) { try { setDialog(await api<TransferDetail>(`/transfers/${t.id}?branchId=${branchId}`)); } catch (e) { setError((e as Error).message); } }
  const warehouseName = (id: string) => { const warehouse = warehouses.find(w => w.id === id); return warehouse ? `${warehouse.branchName} · ${warehouse.name}` : 'Bodega no disponible'; };
  return <><Heading eyebrow="MOVIMIENTO ENTRE BODEGAS" title="Traslados" action={canWrite && <button className="primary" onClick={() => setDialog('new')}>+ Nuevo traslado</button>}>Despacha desde una bodega y recibe por partes en el destino.</Heading>{error && <Notice error>{error}</Notice>}
    <section className="panel">{!transfers.length && <p className="empty">No hay traslados registrados en esta sucursal.</p>}{[...transfers].reverse().map(t => <article className="catalog-row" key={t.id}><div><span className="eyebrow">{t.dispatched ? 'DESPACHADO' : 'BORRADOR'}</span><h2>{warehouseName(t.sourceWarehouseId)} → {warehouseName(t.targetWarehouseId)}</h2><p>Recibido: {qty(t.receivedQuantity)} de {qty(t.requestedQuantity)} unidades base</p></div><button className="secondary" onClick={() => void open(t)}>Gestionar</button></article>)}</section>
    {dialog === 'new' && <TransferForm branchId={branchId} warehouses={warehouses} items={items} close={() => setDialog(null)} saved={async () => { setDialog(null); await refresh(); }} />}{dialog && dialog !== 'new' && <TransferDetailForm detail={dialog} branchId={branchId} warehouses={warehouses} items={items} close={() => setDialog(null)} saved={async () => { setDialog(null); await refresh(); }} />}</>;
}
function TransferForm({ branchId, warehouses, items, close, saved }: { branchId: string; warehouses: WarehouseChoice[]; items: Item[]; close: () => void; saved: () => Promise<void> }) {
  const send = useOperation(branchId); const [lines, setLines] = useState<Line[]>([newLine()]); const initialSource = warehouses.find(w => w.branchId === branchId && w.isDefault)?.id ?? warehouses.find(w => w.branchId === branchId)?.id ?? ''; const [source, setSource] = useState(initialSource); const [target, setTarget] = useState(() => warehouses.find(w => w.id !== initialSource && w.isDefault)?.id ?? warehouses.find(w => w.id !== initialSource)?.id ?? ''); const label = (warehouse: WarehouseChoice) => `${warehouse.branchName} · ${warehouse.name}`;
  return <Dialog title="Nuevo traslado" onClose={close}><SaveForm label="Guardar borrador" onSave={async d => { await send('/transfers', { sourceWarehouseId: value(d, 'source'), targetWarehouseId: value(d, 'target'), reason: value(d, 'reason'), lines: lines.map(l => ({ itemId: l.itemId, quantity: l.quantity, unit: l.unit, conversion: null })) }); await saved(); }}><div className="fields"><label>Origen<select name="source" value={source} required onChange={e => { const next = e.target.value; setSource(next); if (target === next) setTarget(warehouses.find(w => w.id !== next && w.isDefault)?.id ?? warehouses.find(w => w.id !== next)?.id ?? ''); }}>{warehouses.filter(w => w.branchId === branchId).map(w => <option key={w.id} value={w.id}>{label(w)}</option>)}</select></label><label>Destino<select name="target" value={target} required onChange={e => setTarget(e.target.value)}><option value="" disabled>Selecciona otra bodega</option>{warehouses.filter(w => w.id !== source).map(w => <option key={w.id} value={w.id}>{label(w)}</option>)}</select></label></div><p className="muted">El origen corresponde a la sucursal actual; elige la bodega de destino, incluso si pertenece a otra sucursal autorizada.</p>{lines.map((l, n) => <div className="fields" key={l.id}><label>Artículo {n + 1}<select value={l.itemId} required onChange={e => { const i = items.find(x => x.id === e.target.value); setLines(lines.map(x => x.id === l.id ? { ...x, itemId: e.target.value, unit: i?.baseUnit ?? '' } : x)); }}><option value="">Selecciona</option>{items.map(i => <option key={i.id} value={i.id}>{i.name} ({i.baseUnit})</option>)}</select></label><label>Cantidad<input value={l.quantity} inputMode="decimal" required onChange={e => setLines(lines.map(x => x.id === l.id ? { ...x, quantity: e.target.value } : x))} /></label><label>Unidad<input value={l.unit} readOnly /></label>{lines.length > 1 && <button type="button" className="secondary" onClick={() => setLines(lines.filter(x => x.id !== l.id))}>Quitar</button>}</div>)}<button type="button" className="secondary" onClick={() => setLines([...lines, newLine()])}>+ Agregar artículo</button><Reason /></SaveForm></Dialog>;
}
function TransferDetailForm({ detail, branchId, warehouses, items, close, saved }: { detail: TransferDetail; branchId: string; warehouses: WarehouseChoice[]; items: Item[]; close: () => void; saved: () => Promise<void> }) {
  const send = useOperation(branchId); const [receipt, setReceipt] = useState<Record<string, string>>({}); const name = (id: string) => { const warehouse = warehouses.find(w => w.id === id); return warehouse ? `${warehouse.branchName} · ${warehouse.name}` : 'Bodega no disponible'; }; const source = name(detail.sourceWarehouseId); const target = name(detail.targetWarehouseId);
  return <Dialog title={`Traslado: ${source} → ${target}`} onClose={close}><SaveForm label={detail.dispatched ? 'Registrar recepción' : 'Despachar traslado'} onSave={async d => { if (!detail.dispatched) await send(`/transfers/${detail.id}/dispatch`, { reason: value(d, 'reason') }); else await send(`/transfers/${detail.id}/receive`, { reason: value(d, 'reason'), lines: detail.lines.filter(l => receipt[l.id]).map(l => ({ lineId: l.id, quantity: receipt[l.id] })) }); await saved(); }}><p className="muted">{detail.dispatched ? 'Registra solo las cantidades físicas que llegaron.' : 'El despacho descuenta el origen una sola vez.'}</p>{detail.lines.map(l => { const remaining = Number(l.baseQuantity) - Number(l.receivedQuantity); return <div className="fields" key={l.id}><p>{items.find(i => i.id === l.itemId)?.name ?? 'Artículo'} · {qty(l.receivedQuantity)} de {qty(l.baseQuantity)} recibidas</p>{detail.dispatched && remaining > 0 && <label>Recibir ahora<input inputMode="decimal" value={receipt[l.id] ?? ''} onChange={e => setReceipt({ ...receipt, [l.id]: e.target.value })} /></label>}</div>; })}<Reason /></SaveForm></Dialog>;
}

export function Counts({ me, branchId }: { me: Me; branchId: string }) {
  const [warehouses, setWarehouses] = useState<Warehouse[]>([]); const [items, setItems] = useState<Item[]>([]); const [warehouse, setWarehouse] = useState(''); const [dialog, setDialog] = useState<'count' | 'internal' | null>(null); const [error, setError] = useState('');
  useEffect(() => { void (async () => { try { const [b, i] = await Promise.all([api<BranchDetail>(`/branches/${branchId}`), allPages<Item>(`/items?branchId=${branchId}`)]); setWarehouses(b.warehouses); setWarehouse(b.warehouses.find(w => w.isDefault)?.id ?? b.warehouses[0]?.id ?? ''); setItems(i.filter(i => i.kind !== 'finished')); } catch (e) { setError((e as Error).message); } })(); }, [branchId]);
  return <><Heading eyebrow="INVENTARIO FÍSICO" title="Conteos y ajustes" action={me.user.actions.includes('inventory.manage') && <div className="row-actions"><button className="secondary" disabled={!warehouse} onClick={() => setDialog('internal')}>+ Consumo interno</button><button className="primary" disabled={!warehouse} onClick={() => setDialog('count')}>+ Registrar conteo</button></div>}>El sistema conserva la diferencia como ajuste causal; no modifica movimientos anteriores.</Heading>{error && <Notice error>{error}</Notice>}<section className="panel"><label>Bodega<select value={warehouse} onChange={e => setWarehouse(e.target.value)}>{warehouses.map(w => <option key={w.id} value={w.id}>{w.name}</option>)}</select></label><p className="muted">Registra cantidades en su unidad base. El saldo esperado se calcula en el servidor al confirmar.</p></section>{dialog === 'count' && <CountForm branchId={branchId} warehouseId={warehouse} items={items} close={() => setDialog(null)} />}{dialog === 'internal' && <InternalConsumptionForm branchId={branchId} warehouseId={warehouse} items={items} close={() => setDialog(null)} />}</>;
}
function CountForm({ branchId, warehouseId, items, close }: { branchId: string; warehouseId: string; items: Item[]; close: () => void }) { const send = useOperation(branchId); const [lines, setLines] = useState<Line[]>([newLine()]); return <Dialog title="Registrar conteo físico" onClose={close}><SaveForm label="Confirmar conteo" onSave={async d => { await send(`/warehouses/${warehouseId}/counts`, { reason: value(d, 'reason'), lines: lines.map(l => ({ itemId: l.itemId, quantity: l.quantity, unit: l.unit, conversion: null })) }); close(); }}><p className="muted">Incluye solo artículos que acabas de contar.</p>{lines.map((l, n) => <div className="fields" key={l.id}><label>Artículo {n + 1}<select value={l.itemId} required onChange={e => { const i = items.find(x => x.id === e.target.value); setLines(lines.map(x => x.id === l.id ? { ...x, itemId: e.target.value, unit: i?.baseUnit ?? '' } : x)); }}><option value="">Selecciona</option>{items.map(i => <option key={i.id} value={i.id}>{i.name} ({i.baseUnit})</option>)}</select></label><label>Cantidad contada<input value={l.quantity} inputMode="decimal" required onChange={e => setLines(lines.map(x => x.id === l.id ? { ...x, quantity: e.target.value } : x))} /></label><label>Unidad<input value={l.unit} readOnly /></label>{lines.length > 1 && <button type="button" className="secondary" onClick={() => setLines(lines.filter(x => x.id !== l.id))}>Quitar</button>}</div>)}<button type="button" className="secondary" onClick={() => setLines([...lines, newLine()])}>+ Agregar artículo</button><Reason /></SaveForm></Dialog>; }
function InternalConsumptionForm({ branchId, warehouseId, items, close }: { branchId: string; warehouseId: string; items: Item[]; close: () => void }) { const send = useOperation(branchId); const [lines, setLines] = useState<Line[]>([newLine()]); return <Dialog title="Registrar consumo interno" onClose={close}><SaveForm label="Registrar consumo" onSave={async d => { await send(`/warehouses/${warehouseId}/internal-consumptions`, { reason: value(d, 'reason'), lines: lines.map(l => ({ itemId: l.itemId, quantity: l.quantity, unit: l.unit, conversion: null })) }); close(); }}><p className="muted">Esta salida no es una venta ni un desperdicio.</p>{lines.map((l, n) => <div className="fields" key={l.id}><label>Artículo {n + 1}<select value={l.itemId} required onChange={e => { const i = items.find(x => x.id === e.target.value); setLines(lines.map(x => x.id === l.id ? { ...x, itemId: e.target.value, unit: i?.baseUnit ?? '' } : x)); }}><option value="">Selecciona</option>{items.map(i => <option key={i.id} value={i.id}>{i.name} ({i.baseUnit})</option>)}</select></label><label>Cantidad consumida<input value={l.quantity} inputMode="decimal" required onChange={e => setLines(lines.map(x => x.id === l.id ? { ...x, quantity: e.target.value } : x))} /></label><label>Unidad<input value={l.unit} readOnly /></label>{lines.length > 1 && <button type="button" className="secondary" onClick={() => setLines(lines.filter(x => x.id !== l.id))}>Quitar</button>}</div>)}<button type="button" className="secondary" onClick={() => setLines([...lines, newLine()])}>+ Agregar artículo</button><Reason /></SaveForm></Dialog>; }
