import { useEffect, useRef, useState } from 'react';
import { api } from './api.ts';
import type { Me } from './api.ts';
import { Heading, Notice, Dialog, SaveForm, Reason } from './components.tsx';
import { money, when } from './OrderForms.tsx';
import type { LoyaltyCache } from '../src/loyalty.ts';
import type { Customer } from '../src/orders-domain.ts';
export function Loyalty({branchId,me}:{branchId:string;me:Me}){
 const [cache,setCache]=useState<LoyaltyCache|null>(null),[customers,setCustomers]=useState<Customer[]>([]),[search,setSearch]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState<'rules'|'adjust'|'history'|null>(null),[customer,setCustomer]=useState<Customer|null>(null),[history,setHistory]=useState<{id:string;delta:string;balanceAfter:string;reason:string;occurredAtMs:number}[]>([]);
 const operation=useRef({key:'',id:''});const owner=me.user.role==='owner'&&me.user.actions.includes('loyalty.adjust');
 async function refresh(){const c=await api<LoyaltyCache>('/loyalty?branchId='+branchId);const all:Customer[]=[];let after:string|null=null;do{const r:{items:Customer[];nextCursor:string|null}=await api('/customers?branchId='+branchId+(after?'&after='+encodeURIComponent(after):''));all.push(...r.items);after=r.nextCursor;}while(after);setCache(c);setCustomers(all);}
 useEffect(()=>{void refresh().catch(e=>setError(e.message));},[branchId]);
 async function work(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function mutate(route:string,body:object){const key=JSON.stringify({route,...body});if(operation.current.key!==key)operation.current={key,id:crypto.randomUUID()};await api('/loyalty/'+route,'POST',{...body,branchId,operationId:operation.current.id});operation.current={key:'',id:''};await refresh();setModal(null);}
 async function show(c:Customer){const all:typeof history=[];let after:string|null=null;do{const r:{items:typeof history;nextCursor:string|null}=await api('/loyalty/history?branchId='+branchId+'&customerId='+c.id+(after?'&after='+encodeURIComponent(after):''));all.push(...r.items);after=r.nextCursor;}while(after);setHistory(all.sort((a,b)=>b.occurredAtMs-a.occurredAtMs));setCustomer(c);setModal('history');}
 return <><Heading eyebrow="CADA COMPRA CUENTA" title="Fidelización" action={owner&&<button className="secondary" disabled={!cache||busy} onClick={()=>setModal('rules')}>Cambiar reglas</button>}>Inscripción voluntaria, puntos por productos y canje online.</Heading>{error&&<Notice error>{error}</Notice>}{cache&&<section className="panel loyalty-overview"><h2>Reglas actuales</h2><p>1 punto por cada {money(cache.rule.earnEvery)} pagados en productos. Cada punto vale {money(cache.rule.pointValue)}. Canje máximo: {cache.rule.maxPercent}%.</p><p>Sin vencimiento. Se excluyen propinas, domicilio y pagos con puntos.</p><small>Saldos globales confirmados al {when(cache.asOfMs)}. Los puntos offline pendientes aún no están incluidos.</small><button className="secondary" disabled={busy} onClick={()=>void work(refresh)}>Actualizar saldos</button></section>}<section className="panel movement-panel"><div className="panel-toolbar"><label>Buscar cliente en fidelización<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nombre, documento o celular"/></label></div>{customers.filter(c=>(c.name+' '+c.document+' '+c.phone).toLowerCase().includes(search.toLowerCase())).map(c=>{const member=cache?.members.find(m=>m.customerId===c.id);return <article className="catalog-row" key={c.id}><div><h2>{c.name}</h2><p>{c.document} · {c.phone}</p><strong>{member?member.balance+' puntos':'No inscrito'}</strong>{member&&BigInt(member.balance)<0n&&<p>Saldo negativo: puede comprar; canje no disponible.</p>}</div><div className="row-actions">{member?<><button className="secondary" disabled={busy} onClick={()=>void work(()=>show(c))}>Historia de puntos · {c.name}</button>{owner&&<button className="secondary" disabled={busy} onClick={()=>{setCustomer(c);setModal('adjust');}}>Ajustar puntos · {c.name}</button>}</>:<button className="primary" disabled={busy||!me.user.actions.includes('loyalty.enroll')} onClick={()=>void work(()=>mutate('enroll',{customerId:c.id}))}>Inscribir · {c.name}</button>}</div></article>;})}{!customers.length&&<p className="empty">Crea un cliente en Clientes para inscribirlo.</p>}</section>
 {modal==='rules'&&cache&&<Dialog title="Cambiar reglas de puntos" onClose={()=>setModal(null)}><SaveForm label="Guardar nueva regla" onSave={d=>mutate('rules',{earnEvery:String(d.get('earnEvery')),pointValue:String(d.get('pointValue')),maxPercent:String(d.get('maxPercent')),reason:String(d.get('reason'))})}><Notice>La nueva versión se descarga en las cajas al sincronizar. Los comprobantes anteriores conservan su regla. Sin vencimiento.</Notice><label>Productos pagados por punto (COP)<input name="earnEvery" defaultValue={cache.rule.earnEvery} inputMode="numeric" required pattern="[1-9][0-9]*"/></label><label>Valor por punto (COP)<input name="pointValue" defaultValue={cache.rule.pointValue} inputMode="numeric" required pattern="[1-9][0-9]*"/></label><label>Límite de canje (%)<input name="maxPercent" defaultValue={cache.rule.maxPercent} type="number" min="1" max="100" step="1" required/></label><Reason/></SaveForm></Dialog>}
 {modal==='adjust'&&customer&&<Dialog title={'Ajustar puntos de '+customer.name} onClose={()=>setModal(null)}><SaveForm label="Registrar ajuste" onSave={d=>mutate('adjust',{customerId:customer.id,delta:String(d.get('delta')),reason:String(d.get('reason'))})}><Notice>Se agrega un movimiento al historial. Usa un número negativo para restar; el saldo puede quedar negativo.</Notice><label>Puntos a sumar o restar<input name="delta" inputMode="numeric" required pattern="-?[0-9]+"/></label><Reason/></SaveForm></Dialog>}
 {modal==='history'&&customer&&<Dialog title={'Puntos de '+customer.name} onClose={()=>setModal(null)}><Notice>Movimientos sincronizados de {branchId==='centro'?'Centro':'Milán'}. El saldo mostrado en el directorio es global.</Notice>{history.map(h=><article key={h.id} className="catalog-row"><div><strong>{h.delta} puntos</strong><p>{h.reason}</p><small>{when(h.occurredAtMs)} · Saldo global tras movimiento: {h.balanceAfter}</small></div></article>)}{!history.length&&<p>No hay movimientos en esta sucursal.</p>}</Dialog>}</>;
}
