import { useEffect, useState } from 'react';
import { api, date } from './api.ts';
import { Heading, Notice } from './components.tsx';

type Intent = { id:string; type:'low_stock_daily'|'shift_closed'; recipientRole:'owner'|'branch_manager'; state:string; data:Record<string,unknown>; createdAt:string };
const type = (value:Intent['type']) => value === 'low_stock_daily' ? 'Resumen de mínimos' : 'Cierre confirmado';
const recipient = (value:Intent['recipientRole']) => value === 'owner' ? 'Dueño' : 'Encargado del local';
export function Notifications({ branchId }: { branchId:string }) {
  const [items,setItems]=useState<Intent[]>([]);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [state,setState]=useState('');
  const load=async()=>{setBusy(true);setError('');try{const result=await api<{items:Intent[]}>(`/notifications?branchId=${encodeURIComponent(branchId)}${state?`&state=${state}`:''}`);setItems(result.items);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  useEffect(()=>{void load();},[branchId,state]);
  async function simulate(intent:Intent,outcome:'delivered'|'retryable'|'terminal'|'uncertain'){setBusy(true);setError('');try{const result=await api<{state:string}>(`/notifications/${intent.id}/simulate`,'POST',{operationId:crypto.randomUUID(),reason:'Simulación local de resultado de notificación',outcome});setNotice(`Resultado simulado: ${result.state}. No se envió ningún mensaje.`);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <><Heading eyebrow="COLA LOCAL" title="Notificaciones" action={<button className="secondary" disabled={busy} onClick={()=>void load()}>Actualizar</button>}>Intenciones confirmadas para WhatsApp. Esta pantalla no envía mensajes ni contiene números o credenciales.</Heading>
    {error&&<Notice error>{error}</Notice>}{notice&&<Notice>{notice}</Notice>}<section className="panel"><div className="panel-toolbar"><label>Estado<select value={state} onChange={e=>setState(e.target.value)}><option value="">Todos</option><option value="pending">Pendiente</option><option value="failed_retryable">Reintentable</option><option value="uncertain">Incierto</option><option value="delivered">Simulado entregado</option></select></label><span className="muted">Hora de Colombia · Sin proveedor configurado</span></div><div className="table-wrap"><table><thead><tr><th>Creado</th><th>Tipo</th><th>Destinatario lógico</th><th>Estado</th><th>Prueba local</th></tr></thead><tbody>{items.map(intent=><tr key={intent.id}><td>{date(intent.createdAt)}</td><td>{type(intent.type)}</td><td>{recipient(intent.recipientRole)}</td><td>{intent.state}</td><td>{['pending','failed_retryable'].includes(intent.state)?<><button className="secondary" disabled={busy} onClick={()=>void simulate(intent,'delivered')}>Simular entrega</button> <button className="secondary" disabled={busy} onClick={()=>void simulate(intent,'uncertain')}>Simular incierto</button></>:<span className="muted">Sin reenvío automático</span>}</td></tr>)}</tbody></table>{!items.length&&<p className="empty" role="status">{busy?'Cargando intenciones…':'No hay notificaciones confirmadas para esta sucursal.'}</p>}</div></section></>;
}
