import { useEffect, useState } from 'react';
import { Heading, Notice } from './components.tsx';
import { api } from './api.ts';

const kinds = [{ id: 'sales', name: 'Ventas' }, { id: 'cash', name: 'Caja' }, { id: 'inventory', name: 'Inventario' }, { id: 'purchases', name: 'Compras' }, { id: 'waste', name: 'Desperdicio y consumo' }, { id: 'loyalty', name: 'Fidelización' }];
const money = (value: string) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(Number(value));
type Report = { context: { lastSynchronizedAt: Record<string, string | null> }; items: Record<string, unknown>[]; totals: Record<string, string>; nextCursor: string | null };
type Choice = { id: string; name: string };
const methods = [{ id: 'cash', name: 'Efectivo' }, { id: 'card', name: 'Tarjeta' }, { id: 'transfer', name: 'Transferencia' }, { id: 'breb', name: 'Bre-B' }, { id: 'daviplata', name: 'Daviplata' }, { id: 'nequi', name: 'Nequi' }];
export function Reports({ branchId }: { branchId: string }) {
  const [kind, setKind] = useState('sales'); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [productId, setProductId] = useState(''); const [customerId, setCustomerId] = useState(''); const [supplierId, setSupplierId] = useState(''); const [paymentMethod, setPaymentMethod] = useState(''); const [products, setProducts] = useState<Choice[]>([]); const [customers, setCustomers] = useState<Choice[]>([]); const [suppliers, setSuppliers] = useState<Choice[]>([]); const [report, setReport] = useState<Report | null>(null); const [error, setError] = useState('');
  const query = () => new URLSearchParams({ branchId, limit: '20', ...(from ? { from } : {}), ...(to ? { to } : {}), ...((kind === 'sales' || kind === 'waste') && productId ? { productId } : {}), ...((kind === 'sales' || kind === 'loyalty') && customerId ? { customerId } : {}), ...(kind === 'purchases' && supplierId ? { supplierId } : {}), ...((kind === 'sales' || kind === 'purchases') && paymentMethod ? { paymentMethod } : {}) });
  async function load() { setError(''); try { setReport(await api<Report>(`/reports/${kind}?${query()}`)); } catch (e) { setError((e as Error).message); } }
  async function exportXlsx() { setError(''); try { const response = await fetch(`/api/reports/${kind}/export?${query()}`, { credentials: 'same-origin', cache: 'no-store' }); if (!response.ok) { const body = await response.json() as { message?: string }; throw new Error(body.message ?? 'No se pudo exportar el informe.'); } const url = URL.createObjectURL(await response.blob()); const link = document.createElement('a'); link.href = url; link.download = `nativos-${kind}.xlsx`; link.click(); URL.revokeObjectURL(url); } catch (e) { setError((e as Error).message); } }
  useEffect(() => { void load(); }, [branchId, kind]);
  useEffect(() => { void Promise.all([api<{ items: Choice[] }>(`/products?branchId=${branchId}&limit=100`), api<{ items: Choice[] }>(`/customers?branchId=${branchId}`)]).then(([product, customer]) => { setProducts(product.items); setCustomers(customer.items); }).catch(() => { setProducts([]); setCustomers([]); }); }, [branchId]);
  useEffect(() => { void api<{ items: Choice[] }>(`/suppliers?branchId=${branchId}`).then(result => setSuppliers(result.items)).catch(() => setSuppliers([])); }, [branchId]);
  return <><Heading eyebrow="CONSULTA ONLINE" title="Informes">Los totales provienen del libro confirmado; no incluyen costos ni márgenes mientras DEC-005 siga pendiente.</Heading><section className="panel"><div className="fields"><label>Informe<select value={kind} onChange={e => setKind(e.target.value)}>{kinds.map(option => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label><label>Desde<input type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label>Hasta<input type="date" value={to} onChange={e => setTo(e.target.value)} /></label>{(kind === 'sales' || kind === 'waste') && <label>Producto<select value={productId} onChange={e => setProductId(e.target.value)}><option value="">Todos</option>{products.map(option => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label>}{(kind === 'sales' || kind === 'loyalty') && <label>Cliente<select value={customerId} onChange={e => setCustomerId(e.target.value)}><option value="">Todos</option>{customers.map(option => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label>}{kind === 'purchases' && <label>Proveedor<select value={supplierId} onChange={e => setSupplierId(e.target.value)}><option value="">Todos</option>{suppliers.map(option => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label>}{(kind === 'sales' || kind === 'purchases') && <label>Medio<select value={paymentMethod} onChange={e => setPaymentMethod(e.target.value)}><option value="">Todos</option>{methods.map(option => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label>}<button className="secondary" onClick={() => void load()}>Aplicar filtros</button><button className="primary" onClick={() => void exportXlsx()}>Exportar Excel</button></div>{error && <Notice error>{error}</Notice>}{report && <><div className="summary-grid">{Object.entries(report.totals).filter(([, value]) => value !== '0').map(([label, value]) => <section className="stat-card" key={label}><span className="eyebrow">{label}</span><strong>{money(value)}</strong></section>)}</div><p className="small">Última sincronización: {Object.values(report.context.lastSynchronizedAt).some(Boolean) ? Object.values(report.context.lastSynchronizedAt).filter(Boolean).join(' · ') : 'Sin confirmar'}</p><div className="table-wrap"><table><thead><tr>{Object.keys(report.items[0] ?? {}).filter(key => key !== 'id').map(key => <th key={key}>{key}</th>)}</tr></thead><tbody>{report.items.map(item => <tr key={String(item.id)}>{Object.entries(item).filter(([key]) => key !== 'id').map(([key, value]) => <td key={key}>{typeof value === 'object' ? JSON.stringify(value) : String(value ?? '')}</td>)}</tr>)}</tbody></table>{!report.items.length && <p className="empty">No hay registros para estos filtros.</p>}</div>{report.nextCursor && <Notice>La pantalla muestra una página; Excel incluye todas las filas autorizadas.</Notice>}</>}</section></>;
}
