import {locked,readState,writeState} from './storage.ts';
import {hash,passwordHash,verifyPassword,verify} from './crypto.ts';
import {authorize} from '../../src/authorization.ts';
import {isRetryableInventoryRejection,rebaseOperations,transition} from '../../src/sync.ts';
import {decimal,formatted} from '../../src/catalog.ts';
import {signedDecimal} from '../../src/pos-domain.ts';
import {applyOrderEvent,eventAction,upgradeOrder,describeLine} from '../../src/orders-domain.ts';
import type {OrderV2,OrderEvent,CommandEvent,Customer,SaleV2,RefundV2} from '../../src/orders-domain.ts';
import type {Authorization,Signed,Snapshot,PosEvent,CashMovement,CashMovementClass,PaymentMethod} from '../../src/pos-domain.ts';
import type {Operation,Action} from '../../src/contracts.ts';
import type {LoyaltyCache} from '../../src/loyalty.ts';
import type {Shift,Outbox} from '../../src/pos/store.ts';
import * as shape from './generated/validators.js';
type Result=ReturnType<typeof applyOrderEvent>&{cashMovement?:CashMovement};
type Entry={operation:Operation;payload:string;signedId:string;state:Outbox['state'];error:string|null;errorCode?:string|null};
type Staged={entry:Entry;result:Result;fingerprint:string;actorId:string};
export interface BrowserData{
 version:1;installationId:string;sequence:number;previous:string|null;lastSyncAtMs:number|null;high:number;
 terminal?:{deviceId:string;branchId:string;installationId:string;token:string;publicKey:string};
 users:Record<string,{signed:Signed;passwordHash:string;revoked:boolean}>;grants:Record<string,Signed>;
 session:{login:string;expires:number}|null;snapshots:Snapshot[];snapshotId:string|null;customers:Customer[];loyalty:LoyaltyCache|null;
 orders:Record<string,{actorId:string;order:OrderV2}>;selected:Record<string,string>;shifts:Shift[];sales:SaleV2[];refunds:RefundV2[];
 events:{id:string;actorId:string;event:OrderEvent|PosEvent;result:Result}[];stock:{sequence:number;itemId:string;quantity:string}[];
 outbox:Entry[];commands:Record<string,{fingerprint:string;response:Record<string,unknown>}>;staged:Staged|null;
 failures:Record<string,{count:number;until:number}>;retired?:boolean;
 /** Estado aislado de las otras cajas activadas en este mismo navegador. */
 terminalProfiles?:Record<string,BrowserData>;
}
export const blankData=():BrowserData=>({version:1,installationId:crypto.randomUUID(),sequence:0,previous:null,lastSyncAtMs:null,high:0,users:{},grants:{},session:null,snapshots:[],snapshotId:null,customers:[],loyalty:null,orders:{},selected:{},shifts:[],sales:[],refunds:[],events:[],stock:[],outbox:[],commands:{},staged:null,failures:{}});
const legacySequenceConflict='La secuencia ya fue utilizada por otra operación.';
const isSequenceConflict=(entry:Entry)=>entry.state==='reconciliation_required'&&(entry.errorCode==='sequence_conflict'||entry.error===legacySequenceConflict);
class RemoteError extends Error{constructor(public status:number,public code:string,message:string){super(message);}}
let online=false;let message='';const startWall=Date.now(),startMono=performance.now();
export class BrowserEngine{
 constructor(readonly db:IDBDatabase,public data:BrowserData){}
 async save(){await writeState(this.db,this.data);}
 async remote<T>(path:string,body?:unknown,anonymous=false):Promise<T>{let r:Response;try{r=await fetch('/api'+path,{method:body===undefined?'GET':'POST',credentials:anonymous?'omit':'same-origin',cache:'no-store',signal:AbortSignal.timeout(5000),headers:{'Content-Type':'application/json','X-Nativos-Request':'1',...(this.data.terminal?{'X-Pos-Token':this.data.terminal.token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});}catch{online=false;throw new RemoteError(0,'network','Sin conexión. Las operaciones permanecen en este navegador.');}online=true;const value=await r.json();if(!r.ok)throw new RemoteError(r.status,value.code,value.message??'Solicitud rechazada.');return value;}
 loginName(){const s=this.data.session;if(!s||s.expires<=Date.now())throw new Error('Inicia sesión en esta caja.');return s.login;}
 async auth(action:Action='data.read',login=this.loginName()){
  const t=this.data.terminal,u=this.data.users[login];if(!t||!u||u.revoked||this.data.retired)throw new Error('Inicia sesión en esta caja.');const a=await verify(u.signed,t.publicKey);
  if(a.grant.deviceId!==t.deviceId||a.grant.branchId!==t.branchId)throw new Error('Autorización de otra caja.');
  const decision=authorize({principal:a.principal,verifiedGrant:a.grant,action,branchId:t.branchId,deviceId:t.deviceId,mode:'offline',nowMs:Date.now(),lastObservedAtMs:this.data.high});
  if(!decision.allowed)throw new Error(decision.reason==='offline_expired'?'Han pasado siete días. Inicia sesión online para volver a cobrar.':decision.reason==='clock_untrusted'?'El reloj retrocedió. Revalida tu acceso online.':'No tienes permiso para esta operación.');
  if(['sale.charge','sale.refund','shift.open'].includes(action)&&Date.now()+1000<startWall+performance.now()-startMono)throw new Error('El reloj retrocedió. Revalida tu acceso online.');return a;
 }
 async accept(login:string,verifier:string,result:{signed:Signed;snapshot:Snapshot;customers:Customer[];loyalty:LoyaltyCache}){
  const a=await verify(result.signed,this.data.terminal!.publicKey);if(!shape.snapshot(result.snapshot)||result.snapshot.deviceId!==a.grant.deviceId||result.snapshot.branchId!==a.grant.branchId||a.grant.deviceId!==this.data.terminal!.deviceId||a.grant.branchId!==this.data.terminal!.branchId||a.grant.actorId!==a.principal.actorId)throw new Error('Catálogo incompleto. Conserva la descarga anterior.');
  this.data.users[login]={signed:result.signed,passwordHash:verifier,revoked:false};this.data.high=a.grant.validatedAtMs;this.data.customers=result.customers;this.data.loyalty=result.loyalty;
  if(!this.data.outbox.length){
   if(!this.data.staged&&result.snapshot.serverSequence>this.data.sequence){const previous=result.snapshot.serverOperationId;if((result.snapshot.serverSequence===0&&previous!==null)||(result.snapshot.serverSequence>0&&typeof previous!=='string'))throw new Error('El servidor no entregó un cursor de Caja completo.');this.data.sequence=result.snapshot.serverSequence;this.data.previous=previous??null;}
   if(!this.data.snapshots.some(s=>s.id===result.snapshot.id))this.data.snapshots.push(result.snapshot);this.data.snapshotId=result.snapshot.id;this.data.lastSyncAtMs=Date.now();
  }
  await this.save();
 }
 async login(login:string,password:string,sessionExists=false){login=login.toLowerCase();
  try{if(!sessionExists)await this.remote('/login',{login,password});const verifier=password?await passwordHash(password):this.data.users[login]?.passwordHash??'';
   this.data.session={login,expires:Date.now()+12*3600_000};await this.save();
   if(!this.data.terminal){const me=await this.remote<{user:{role:string};branches:{id:string;name:string}[]}>('/me');if(me.user.role!=='owner')throw new Error('El dueño debe activar Caja en este navegador.');const devices=[];for(const b of me.branches){const detail=await this.remote<{devices:{id:string;name:string;active:boolean}[]}>('/branches/'+b.id);devices.push(...detail.devices.filter(d=>d.active).map(d=>({...d,branchName:b.name})));}this.data.users[login]={signed:{document:'',signature:''},passwordHash:verifier,revoked:false};await this.save();return {needsEnrollment:true,devices,needsPassword:!verifier};}
   await this.sync(false);await this.accept(login,verifier,await this.remote('/pos/authorize',{deviceId:this.data.terminal.deviceId,previous:null}));message='';return {needsEnrollment:false};
  }catch(e){if(!(e instanceof RemoteError)||e.status!==0)throw e;const fail=this.data.failures[login];if(fail&&fail.until>Date.now())throw new Error('Espera antes de volver a intentar el acceso offline.');const u=this.data.users[login];if(!u||!u.passwordHash||!await verifyPassword(password,u.passwordHash)){const count=(fail?.count??0)+1;this.data.failures[login]={count,until:count>=5?Date.now()+300000:0};await this.save();throw new Error('Credenciales offline incorrectas.');}await this.auth('data.read',login);this.data.session={login,expires:Date.now()+12*3600_000};delete this.data.failures[login];await this.save();return {needsEnrollment:false};}
 }
 async session(){const me=await this.remote<{user:{login:string}}>('/me');return this.login(me.user.login,'',true);}
 async preparePassword(password:string){const login=this.loginName();if(this.data.users[login]?.passwordHash)return;if(!password)throw new Error('Ingresa tu contraseña para habilitar el acceso sin conexión.');await this.remote('/login',{login,password});this.data.users[login]!.passwordHash=await passwordHash(password);await this.save();}
 async enroll(deviceId:string){const login=this.loginName();this.data.terminal=await this.remote('/pos/enroll',{deviceId,installationId:this.data.installationId});await this.save();await this.accept(login,this.data.users[login]!.passwordHash,await this.remote('/pos/authorize',{deviceId,previous:null}));await navigator.storage?.persist?.();return {ok:true};}
 async terminals(){const me=await this.remote<{branches:{id:string;name:string}[]}>('/me');const devices:{id:string;name:string;branchName:string}[]=[];for(const branch of me.branches){const detail=await this.remote<{devices:{id:string;name:string;active:boolean}[]}>('/branches/'+branch.id);devices.push(...detail.devices.filter(d=>d.active).map(d=>({id:d.id,name:d.name,branchName:branch.name})));}return devices;}
 async switchTerminal(deviceId:string){
  const current=this.data.terminal;if(!current||current.deviceId===deviceId)return this.state();
  await this.sync();
  if(this.data.outbox.length||this.data.staged)throw new Error('Sincroniza o resuelve los pendientes antes de cambiar de sucursal.');
  if(this.shift())throw new Error('Cierra el turno actual antes de cambiar de sucursal.');
  const login=this.loginName(), user=structuredClone(this.data.users[login]!);
  const profiles=this.data.terminalProfiles??{};
  const {terminalProfiles:_ignored,...currentProfile}=structuredClone(this.data);
  profiles[current.deviceId]=currentProfile;
  const saved=profiles[deviceId];
  if(saved){
   this.data=structuredClone(saved);this.data.terminalProfiles=profiles;this.data.session={login,expires:Date.now()+12*3600_000};this.data.users[login]=user;
   await this.sync(false);await this.accept(login,user.passwordHash,await this.remote('/pos/authorize',{deviceId,previous:null}));
  }else{
   const next=blankData();next.installationId=current.installationId;next.session={login,expires:Date.now()+12*3600_000};next.users[login]=user;next.terminalProfiles=profiles;this.data=next;
   await this.enroll(deviceId);
  }
  return this.state();
 }
 shift(){return this.data.shifts.find(s=>s.closedAtMs===null)??null;}
 snapshot(){return this.data.snapshots.find(s=>s.id===this.data.snapshotId)??null;}
 current(actorId:string){const list=Object.values(this.data.orders).filter(o=>o.actorId===actorId&&!o.order.closed);return list.find(o=>o.order.id===this.data.selected[actorId])?.order??list.at(-1)?.order??upgradeOrder({id:crypto.randomUUID(),revision:0,snapshotId:this.data.snapshotId??'',lines:[]});}
 async state(){const a=await this.auth();let canCharge=true,restriction='',canRefund=true,canReauthorize=false;try{await this.auth('sale.charge');}catch(e){canCharge=false;const reason=(e as Error).message;canReauthorize=reason==='El reloj retrocedió. Revalida tu acceso online.';restriction=canReauthorize?'':reason;}try{await this.auth('sale.refund');}catch{canRefund=false;}
  const d=this.data,order=this.current(a.grant.actorId),snapshot=this.snapshot(),shift=this.shift(),lastClosedShift=d.shifts.filter(s=>s.closedAtMs!==null).at(-1)??null;const stock=new Map(snapshot?.stock.map(i=>[i.itemId,signedDecimal(i.quantity)])??[]);for(const m of d.stock.filter(m=>m.sequence>(snapshot?.serverSequence??0)))stock.set(m.itemId,(stock.get(m.itemId)??0n)+signedDecimal(m.quantity));
  let tip=0n,shipping=0n;for(const e of d.events.filter(e=>e.event.shiftId===(shift?.id??lastClosedShift?.id))){if(e.result.sale){tip+=signedDecimal(e.result.sale.tipPaid);shipping+=signedDecimal(e.result.sale.shippingPaid);}if(e.result.refund){tip-=signedDecimal(e.result.refund.tip);shipping-=signedDecimal(e.result.refund.shipping);}}
  const loyaltyPending=d.outbox.flatMap(o=>{const s=d.sales.find(s=>s.id===o.operation.operationId);if(s?.loyalty)return[{id:s.id,customerId:s.customer!.id,earned:s.loyalty.earnedPoints,reversed:'0',restored:'0'}];const r=d.refunds.find(r=>r.id===o.operation.operationId);return r?.loyalty?[{id:r.id,customerId:r.loyalty.customerId,earned:'0',reversed:r.loyalty.earnedReversed,restored:r.loyalty.redeemedRestored}]:[];});
  const reconciliation=d.outbox.find(o=>o.state==='reconciliation_required');const syncBlocked=Boolean(reconciliation);if(syncBlocked){canCharge=false;restriction='Concilia las operaciones pendientes antes de continuar.';canRefund=false;}
  return {user:{id:a.grant.actorId,name:a.actorName},branchId:a.grant.branchId,deviceId:a.grant.deviceId,expiresAtMs:a.grant.expiresAtMs,online,message,canCharge:canCharge&&!d.staged,canCashMovement:a.principal.actions.includes('cash.movement')&&!d.staged&&!syncBlocked,restriction,canReauthorize,canRefund,snapshot,orderSnapshots:d.snapshots,snapshots:d.snapshots,order,orders:Object.values(d.orders).filter(o=>o.actorId===a.grant.actorId&&!o.order.closed).map(o=>o.order),customers:d.customers,shift,lastClosedShift,shiftSummary:{tip:formatted(tip),shipping:formatted(shipping)},preview:order.lines.length?{lines:order.lines.map(l=>describeLine(l,d.snapshots)),total:formatted(order.lines.reduce((n,l)=>n+decimal(describeLine(l,d.snapshots).amount),0n))}:null,sales:d.sales.slice(-50).reverse(),refunds:d.refunds,cashMovements:d.events.filter(e=>e.event.shiftId===(shift?.id??lastClosedShift?.id)).flatMap(e=>e.result.cashMovement?[e.result.cashMovement]:[]).reverse(),events:d.events.filter(e=>e.actorId===a.grant.actorId).slice(-50).reverse(),stock:[...stock].map(([itemId,q])=>({itemId,quantity:formatted(q),negative:q<0n})),pending:d.outbox.map(o=>({id:o.operation.operationId,sequence:o.operation.sequence,state:o.state,error:o.error,errorCode:o.errorCode??null})),reconciliationRequired:syncBlocked,canReconcileSequence:Boolean(reconciliation&&isSequenceConflict(reconciliation)),canRetryInventoryRejection:Boolean(reconciliation&&isRetryableInventoryRejection(reconciliation)),reconciliationMessage:reconciliation?.error??null,lastSyncAtMs:d.lastSyncAtMs,loyalty:d.loyalty,loyaltyPending,redemptionPending:d.staged?{id:d.staged.entry.operation.operationId,actorId:d.staged.actorId,total:d.staged.result.sale?.total}:null};
 }
 async archive(a:Authorization){this.data.grants[a.grant.grantId]=this.data.users[this.loginName()]!.signed;this.data.high=Math.max(this.data.high,Date.now());}
 ensureWritable(){if(this.data.outbox.some(o=>o.state==='reconciliation_required'))throw new Error('Concilia las operaciones pendientes antes de continuar.');}
 async entry(id:string,event:OrderEvent|PosEvent,a:Authorization,version:1|2|3):Promise<Entry>{const payload=JSON.stringify(event);return {operation:{version:1,operationId:id,deviceId:a.grant.deviceId,branchId:a.grant.branchId,actorId:a.grant.actorId,sequence:this.data.sequence+1,previousOperationId:this.data.previous,payloadHash:await hash(payload),payloadVersion:version},payload,signedId:a.grant.grantId,state:'pending',error:null};}
 async replay(id:string,intent:unknown,actorId:string){const fingerprint=await hash(JSON.stringify({actor:actorId,intent}));const old=this.data.commands[id];if(old&&old.fingerprint!==fingerprint)throw new Error('Identificador utilizado por otro comando.');return {fingerprint,response:old?.response};}
 record(entry:Entry,fingerprint:string,response:Record<string,unknown>){this.data.outbox.push(entry);this.data.sequence=entry.operation.sequence;this.data.previous=entry.operation.operationId;this.data.commands[entry.operation.operationId]={fingerprint,response};}
 apply(staged:Staged){const d=this.data,{result:r,entry:e,actorId}=staged,id=e.operation.operationId;if(r.order){d.orders[r.order.id]={actorId,order:r.order};d.selected[actorId]=r.order.id;}if(r.sale)d.sales.push(r.sale);if(r.refund)d.refunds.push(r.refund);d.events.push({id,actorId,event:JSON.parse(e.payload) as OrderEvent|PosEvent,result:r});if(r.sale||r.refund||r.cashMovement){const s=this.shift()!;s.expected=formatted(signedDecimal(s.expected)+signedDecimal(r.cashDelta));}for(const m of r.movements)d.stock.push({sequence:e.operation.sequence,itemId:m.itemId,quantity:m.quantity});this.record(e,staged.fingerprint,r);}
 async command(id:string,input:CommandEvent){if(!shape.command(input))throw new Error('Revisa los campos del pedido.');let a=await this.auth();const intent={kind:'orders.v2',event:input};const replay=await this.replay(id,intent,a.grant.actorId);if(replay.response)return replay.response;this.ensureWritable();if(this.data.staged)throw new Error('Recupera o cancela el canje pendiente.');await this.auth(eventAction(input));if(input.kind==='order.save'&&input.order.lines.some(l=>l.discount.value!=='0'))await this.auth('sale.discount');
  const redeem=input.kind==='sale.split'&&BigInt(input.points??'0')>0n;if(redeem){if(!a.principal.actions.includes('loyalty.redeem'))throw new Error('No tienes permiso para canjear.');await this.sync(false);if(this.data.outbox.length)throw new Error('Sincroniza los pendientes antes de canjear.');await this.refresh();a=await this.auth('sale.charge');}
  const body=structuredClone(input);if(body.kind==='sale.split'){const p=body.points??'0',quoted=body.ruleId;delete body.points;delete body.ruleId;const cache=this.data.loyalty,member=cache?.members.find(m=>m.customerId===body.customerId);if(quoted&&quoted!==cache?.rule.id)throw new Error('Las reglas cambiaron. Revisa el cobro.');if(redeem&&!member)throw new Error('Inscribe al cliente antes de canjear.');if(cache&&member)body.loyalty={rule:cache.rule,redeemedPoints:p,knownBalance:member.balance,memberSince:member.enrolledAtMs};}
  if('orderId'in body){const old=this.data.orders[body.orderId]?.order;if(old?.revision===0&&body.revision===0){await this.command(crypto.randomUUID(),{kind:'order.save',order:old});body.revision=1;}}
  const event:OrderEvent={...body,occurredAtMs:Date.now(),shiftId:this.shift()?.id??null};const orderId=event.kind==='order.save'?event.order.id:'orderId'in event?event.orderId:null;const owned=orderId?this.data.orders[orderId]:null;if(owned&&owned.actorId!==a.grant.actorId)throw new Error('El pedido pertenece a otro usuario.');const shift=this.shift();if(['sale.split','sale.refund'].includes(event.kind)&&(!shift||shift.actorId!==a.grant.actorId))throw new Error('Abre un turno propio para cobrar o devolver.');
  const cid=event.kind==='sale.split'?event.customerId:event.kind==='order.save'?event.order.customerId:null;const customer=this.data.customers.find(c=>c.id===cid)??null;if(cid&&!customer)throw new Error('Selecciona un cliente sincronizado.');const originalSale=event.kind==='sale.refund'?this.data.sales.find(s=>s.id===event.saleId)??null:null;
  const entry=await this.entry(id,event,a,event.kind==='sale.split'&&event.loyalty||originalSale?.loyalty?3:2);const result=applyOrderEvent(event,{id,receiptNumber:`${a.grant.branchId}-${a.grant.deviceId}-${this.data.installationId}-${entry.operation.sequence}`,actorId:a.grant.actorId,actorName:a.actorName,branchId:a.grant.branchId,deviceId:a.grant.deviceId,order:owned?.order??null,snapshots:this.data.snapshots,customer,originalSale,refunds:originalSale?this.data.refunds.filter(r=>r.saleId===originalSale.id):[]});
  await this.archive(a);const staged={entry,result,fingerprint:replay.fingerprint,actorId:a.grant.actorId};if(redeem){this.data.staged=staged;await this.save();return this.recover();}this.apply(staged);await this.save();return result;
 }
 async shiftCommand(id:string,kind:'shift.open'|'shift.close',value:string){const a=await this.auth();const intent={kind,value};const replay=await this.replay(id,intent,a.grant.actorId);if(replay.response)return replay.response;this.ensureWritable();await this.auth(kind);decimal(value);if(this.data.staged)throw new Error('Resuelve el canje pendiente.');const existing=this.shift();if(kind==='shift.open'?existing!==null:!existing||existing.actorId!==a.grant.actorId)throw new Error('La caja tiene otro turno o no te pertenece.');const now=Date.now();const event:PosEvent=kind==='shift.open'?{kind,shiftId:crypto.randomUUID(),openingCash:value,occurredAtMs:now}:{kind,shiftId:existing!.id,counted:value,occurredAtMs:now};const entry=await this.entry(id,event,a,1);let shift:Shift;if(kind==='shift.open'){shift={id:event.shiftId,actorId:a.grant.actorId,actorName:a.actorName,openingCash:value,expected:value,openedAtMs:now,closedAtMs:null,counted:null,difference:null};this.data.shifts.push(shift);}else{shift=existing!;shift.closedAtMs=now;shift.counted=value;shift.difference=formatted(decimal(value)-signedDecimal(shift.expected));}await this.archive(a);this.record(entry,replay.fingerprint,{shift});await this.save();return {shift};}
 async cashMovementCommand(id:string,input:{class:CashMovementClass;method:PaymentMethod;amount:string;reason:string;reversesMovementId:string|null}){let a=await this.auth();const intent={kind:'cash.movement',...input};const replay=await this.replay(id,intent,a.grant.actorId);if(replay.response)return replay.response;this.ensureWritable();if(this.data.staged)throw new Error('Resuelve el canje pendiente.');if(!a.principal.actions.includes('cash.movement'))throw new Error('No tienes permiso para registrar movimientos de caja.');await this.remote('/me');await this.refresh();a=await this.auth();if(decimal(input.amount)<=0n||input.reason.trim().length<3||input.reason.length>500)throw new Error('Revisa el importe y el motivo.');const shift=this.shift();if(!shift||shift.actorId!==a.grant.actorId)throw new Error('Abre un turno propio antes de registrar el movimiento.');const original=input.reversesMovementId?this.data.events.find(e=>e.result.cashMovement?.id===input.reversesMovementId)?.result.cashMovement:null;if(input.class==='correction'?!original||original.shiftId!==shift.id||original.reversesMovementId!==null||original.method!==input.method||original.amount!==formatted(decimal(input.amount)):input.reversesMovementId!==null)throw new Error('La corrección debe referenciar exactamente un movimiento vigente del turno.');const delta=input.class==='correction'?-signedDecimal(original!.cashDelta):input.method==='cash'?(input.class==='income'?decimal(input.amount):-decimal(input.amount)):0n;const event:PosEvent={kind:'cash.movement',shiftId:shift.id,movementId:crypto.randomUUID(),class:input.class,method:input.method,amount:input.amount,reason:input.reason.trim(),reversesMovementId:input.reversesMovementId,occurredAtMs:Date.now()};const entry=await this.entry(id,event,a,1);const movement:CashMovement={id:event.movementId,shiftId:shift.id,class:event.class,method:event.method,amount:formatted(decimal(event.amount)),cashDelta:formatted(delta),reason:event.reason,reversesMovementId:event.reversesMovementId,occurredAtMs:event.occurredAtMs,actorName:a.actorName};const result:Result={order:null,sale:null,refund:null,comanda:null,movements:[],warehouseId:'',cashDelta:movement.cashDelta,cashMovement:movement};await this.archive(a);this.apply({entry,result,fingerprint:replay.fingerprint,actorId:a.grant.actorId});await this.save();return {cashMovement:movement};}
 async recover(cancel=false){const s=this.data.staged;if(!s)return null;const signed=this.data.grants[s.entry.signedId];if(!signed)throw new Error('Falta autorización histórica.');if(cancel){const result=await this.remote<{committed:boolean}>('/pos/redemption/cancel',{operationId:s.entry.operation.operationId,deviceId:s.entry.operation.deviceId,signed},true);if(!result.committed){this.data.staged=null;await this.save();return null;}}
  const result=await this.remote<{kind:'accepted';receipt:Operation}>('/pos/sync',{operation:s.entry.operation,payload:s.entry.payload,signed},true);if(result.kind!=='accepted'||transition('pending',s.entry.operation,result)!=='acknowledged')throw new Error('Acuse incorrecto. Conserva el intento.');this.apply(s);this.data.outbox=this.data.outbox.filter(o=>o.operation.operationId!==s.entry.operation.operationId);this.data.staged=null;await this.save();return s.result;
 }
 async refresh(){const login=this.loginName(),u=this.data.users[login];if(!u||!this.data.terminal)return;try{const r=await this.remote<{signed:Signed;snapshot:Snapshot;customers:Customer[];loyalty:LoyaltyCache}>('/pos/authorize',{deviceId:this.data.terminal.deviceId,previous:u.signed},true);await this.accept(login,u.passwordHash,r);}catch(e){if(e instanceof RemoteError&&e.status===403){u.revoked=true;await this.save();}throw e;}}
 async reauthorize(){const login=this.loginName(),u=this.data.users[login],terminal=this.data.terminal;if(!u||!terminal)throw new Error('Inicia sesión en esta caja.');const result=await this.remote<{signed:Signed;snapshot:Snapshot;customers:Customer[];loyalty:LoyaltyCache}>('/pos/authorize',{deviceId:terminal.deviceId,previous:null});await this.accept(login,u.passwordHash,result);message='';return this.state();}
 async reconcileSequence(){const conflict=this.data.outbox.find(isSequenceConflict);if(!conflict)throw new Error('No hay un conflicto de secuencia recuperable.');if(this.data.staged)throw new Error('Resuelve primero el canje pendiente.');const login=this.loginName(),u=this.data.users[login]!,result=await this.remote<{signed:Signed;snapshot:Snapshot;customers:Customer[];loyalty:LoyaltyCache}>('/pos/authorize',{deviceId:this.data.terminal!.deviceId,previous:u.signed},true);await this.accept(login,u.passwordHash,result);const cursor={sequence:result.snapshot.serverSequence,operationId:result.snapshot.serverOperationId??null};if(cursor.sequence>0&&!cursor.operationId)throw new Error('El servidor no entregó un cursor de Caja completo.');if(cursor.sequence<conflict.operation.sequence)throw new Error('El cursor central no confirma la colisión. Sincroniza nuevamente.');const old=this.data.outbox.map(o=>o.operation),rebased=rebaseOperations(old,cursor),sequences=new Map(old.map((o,i)=>[o.sequence,rebased[i]!.sequence]));this.data.stock=this.data.stock.map(row=>sequences.has(row.sequence)?{...row,sequence:sequences.get(row.sequence)!}:row);for(let i=0;i<this.data.outbox.length;i++){const entry=this.data.outbox[i]!,operation=rebased[i]!,receiptNumber=`${operation.branchId}-${operation.deviceId}-${this.data.installationId}-${operation.sequence}`;entry.operation=operation;entry.state='pending';entry.error=null;entry.errorCode=null;const sale=this.data.sales.find(s=>s.id===operation.operationId);if(sale)sale.receiptNumber=receiptNumber;const event=this.data.events.find(e=>e.id===operation.operationId);if(event?.result.sale)event.result.sale.receiptNumber=receiptNumber;const response=this.data.commands[operation.operationId]?.response as Result|undefined;if(response?.sale)response.sale.receiptNumber=receiptNumber;}const last=rebased.at(-1)!;this.data.sequence=last.sequence;this.data.previous=last.operationId;message='';await this.save();await this.sync(false);if(!this.data.outbox.length)await this.refresh();return this.state();}
 async retryInventoryRejection(){const rejection=this.data.outbox.find(isRetryableInventoryRejection);if(!rejection)throw new Error('No hay un rechazo de inventario recuperable.');if(this.data.staged)throw new Error('Resuelve primero el canje pendiente.');rejection.state='retry';rejection.error=null;rejection.errorCode=null;message='';await this.save();await this.sync(false);if(!this.data.outbox.length)await this.refresh();return this.state();}
 async sync(refresh=true){if(!this.data.terminal)return;message='';for(const o of [...this.data.outbox]){if(o.state==='reconciliation_required'){const issue=o.error??'Pendiente de conciliación.';try{await this.remote('/me');}catch(e){if(e instanceof RemoteError&&e.status===0){message=e.message;return;}}message=issue;return;}try{const signed=this.data.grants[o.signedId];if(!signed)throw new Error('Falta autorización histórica.');const r=await this.remote<{kind:'accepted';receipt:Operation}>('/pos/sync',{operation:o.operation,payload:o.payload,signed},true);if(r.kind!=='accepted'||transition(o.state,o.operation,r)!=='acknowledged')throw new Error('Acuse incorrecto.');this.data.outbox=this.data.outbox.filter(p=>p.operation.operationId!==o.operation.operationId);await this.save();}catch(e){message=(e as Error).message;o.state=e instanceof RemoteError&&(e.status===0||e.status>=500||e.status===429||e.code==='predecessor_required')?'retry':'reconciliation_required';o.error=message;o.errorCode=e instanceof RemoteError?e.code:null;if(e instanceof RemoteError&&e.code==='device_revoked')for(const u of Object.values(this.data.users))u.revoked=true;await this.save();return;}}
  if(this.data.staged){try{await this.recover();}catch(e){message=(e as Error).message;return;}}if(refresh){try{await this.refresh();}catch(e){message=(e as Error).message;}}
 }
}
export async function useEngine<T>(fn:(e:BrowserEngine)=>Promise<T>){return locked(async db=>{const data=await readState<BrowserData>(db)??blankData();if(data.version!==1)throw new Error('Versión de Caja incompatible. Conserva los datos.');const e=new BrowserEngine(db,data);return fn(e);});}
export async function browserCall<T>(path:string,body:Record<string,unknown>={}):Promise<T>{return useEngine(async e=>{
 let result:unknown;
 if(path==='/login')result=await e.login(String(body.login),String(body.password));
 else if(path==='/session')result=await e.session();
 else if(path==='/import-legacy'){await e.preparePassword(String(body.password??''));const login=e.loginName(),verifier=e.data.users[login]!.passwordHash;if(e.data.terminal||e.data.outbox.length||e.data.sequence)throw new Error('Este navegador ya tiene una caja.');await e.save();const target=e.data.installationId;const imported=await e.remote<BrowserData>('/local-transition',{targetId:target});if(imported.version!==1||!imported.terminal||imported.terminal.installationId!==imported.installationId)throw new Error('Traslado incompatible.');e.data=imported;e.data.users[login]={...(e.data.users[login]??{signed:{document:'',signature:''},revoked:false}),passwordHash:verifier};await e.save();await navigator.storage?.persist?.();result=await e.session();}
 else if(path==='/enroll'){await e.preparePassword(String(body.password??''));result=await e.enroll(String(body.deviceId));}
 else if(path==='/terminals')result=await e.terminals();
 else if(path==='/terminal/switch')result=await e.switchTerminal(String(body.deviceId));
 else if(path==='/logout'){localStorage.setItem('nativos-session-ended',String(Date.now()));e.data.session=null;await e.save();try{await e.remote('/logout',{});}catch{}result={ok:true};}
 else if(path==='/v2/state')result=await e.state();
 else if(path==='/v2/command')result=await e.command(String(body.operationId),body.event as CommandEvent);
 else if(path==='/v2/select'){const a=await e.auth();const row=e.data.orders[String(body.orderId)];if(!row||row.actorId!==a.grant.actorId)throw new Error('Pedido de otro usuario.');e.data.selected[a.grant.actorId]=row.order.id;await e.save();result=await e.state();}
 else if(path==='/shift/open'||path==='/shift/close')result=await e.shiftCommand(String(body.operationId),path==='/shift/open'?'shift.open':'shift.close',String(body.openingCash??body.counted));
 else if(path==='/cash/movement')result=await e.cashMovementCommand(String(body.operationId),body as {class:CashMovementClass;method:PaymentMethod;amount:string;reason:string;reversesMovementId:string|null});
 else if(path==='/sync'){await e.auth();await e.sync();result=await e.state();}
 else if(path==='/sync/reconcile'){await e.auth();result=await e.reconcileSequence();}
 else if(path==='/sync/retry-inventory'){await e.auth();result=await e.retryInventoryRejection();}
 else if(path==='/reauthorize')result=await e.reauthorize();
 else if(path==='/loyalty/resolve'){const a=await e.auth();if(e.data.staged?.actorId!==a.grant.actorId)throw new Error('El canje debe resolverlo su responsable.');result=await e.recover(body.cancel===true);}
 else if(path==='/loyalty/refresh'){await e.auth();await e.refresh();result=e.data.loyalty;}
 else if(path==='/loyalty/enroll'){await e.auth();result=await e.remote('/loyalty/enroll',body);await e.refresh();}
 else throw new Error('Operación de Caja desconocida.');return result as T;
 });}
